const VOCABULARY = [
  // Greetings (15)
  { id: "gt001", ru: "привет", en: "hello", translit: "privet", category: "greetings", example: { ru: "Привет, как дела?", en: "Hello, how are you?" } },
  { id: "gt002", ru: "здравствуйте", en: "good day / hello (formal)", translit: "zdravstvuyte", category: "greetings", example: { ru: "Здравствуйте, я новый студент.", en: "Hello, I am a new student." } },
  { id: "gt003", ru: "до свидания", en: "goodbye", translit: "do svidaniya", category: "greetings", example: { ru: "До свидания, до завтра!", en: "Goodbye, see you tomorrow!" } },
  { id: "gt004", ru: "пока", en: "bye (informal)", translit: "poka", category: "greetings", example: { ru: "Пока, увидимся!", en: "Bye, see you!" } },
  { id: "gt005", ru: "спасибо", en: "thank you", translit: "spasibo", category: "greetings", example: { ru: "Спасибо за помощь.", en: "Thank you for your help." } },
  { id: "gt006", ru: "пожалуйста", en: "please / you're welcome", translit: "pozhaluysta", category: "greetings", example: { ru: "Пожалуйста, помогите мне.", en: "Please help me." } },
  { id: "gt007", ru: "извините", en: "excuse me / sorry", translit: "izvinite", category: "greetings", example: { ru: "Извините, вы не знаете, где банк?", en: "Excuse me, do you know where the bank is?" } },
  { id: "gt008", ru: "да", en: "yes", translit: "da", category: "greetings", example: { ru: "Да, я понимаю.", en: "Yes, I understand." } },
  { id: "gt009", ru: "нет", en: "no", translit: "net", category: "greetings", example: { ru: "Нет, я не хочу чай.", en: "No, I don't want tea." } },
  { id: "gt010", ru: "доброе утро", en: "good morning", translit: "dobroye utro", category: "greetings", example: { ru: "Доброе утро! Как спалось?", en: "Good morning! Did you sleep well?" } },
  { id: "gt011", ru: "добрый день", en: "good afternoon", translit: "dobryy den'", category: "greetings", example: { ru: "Добрый день, я ищу магазин.", en: "Good afternoon, I am looking for a store." } },
  { id: "gt012", ru: "добрый вечер", en: "good evening", translit: "dobryy vecher", category: "greetings", example: { ru: "Добрый вечер, садитесь.", en: "Good evening, please sit down." } },
  { id: "gt013", ru: "спокойной ночи", en: "good night", translit: "spokoynoy nochi", category: "greetings", example: { ru: "Спокойной ночи, до завтра.", en: "Good night, see you tomorrow." } },
  { id: "gt014", ru: "как дела?", en: "how are you?", translit: "kak dela?", category: "greetings", example: { ru: "Как дела? Всё хорошо?", en: "How are you? Is everything okay?" } },
  { id: "gt015", ru: "хорошо", en: "good / fine / well", translit: "khorosho", category: "greetings", example: { ru: "Всё хорошо, спасибо.", en: "Everything is good, thank you." } },

  // Numbers 1–20 (20)
  { id: "nu001", ru: "один", en: "one", translit: "odin", category: "numbers", example: { ru: "У меня один брат.", en: "I have one brother." } },
  { id: "nu002", ru: "два", en: "two", translit: "dva", category: "numbers", example: { ru: "Мне нужно два билета.", en: "I need two tickets." } },
  { id: "nu003", ru: "три", en: "three", translit: "tri", phonetic: "/θriː/", category: "numbers", example: { ru: "В семье три ребёнка.", en: "There are three children in the family." } },
  { id: "nu004", ru: "четыре", en: "four", translit: "chetyre", category: "numbers", example: { ru: "Стол стоит четыре тысячи.", en: "The table costs four thousand." } },
  { id: "nu005", ru: "пять", en: "five", translit: "pyat'", category: "numbers", example: { ru: "Дайте мне пять яблок.", en: "Give me five apples." } },
  { id: "nu006", ru: "шесть", en: "six", translit: "shest'", category: "numbers", example: { ru: "Автобус приходит в шесть часов.", en: "The bus comes at six o'clock." } },
  { id: "nu007", ru: "семь", en: "seven", translit: "sem'", category: "numbers", example: { ru: "В неделе семь дней.", en: "There are seven days in a week." } },
  { id: "nu008", ru: "восемь", en: "eight", translit: "vosem'", category: "numbers", example: { ru: "Встреча в восемь утра.", en: "The meeting is at eight in the morning." } },
  { id: "nu009", ru: "девять", en: "nine", translit: "devyat'", category: "numbers", example: { ru: "Магазин открывается в девять.", en: "The store opens at nine." } },
  { id: "nu010", ru: "десять", en: "ten", translit: "desyat'", category: "numbers", example: { ru: "Я жду уже десять минут.", en: "I have been waiting for ten minutes." } },
  { id: "nu011", ru: "одиннадцать", en: "eleven", translit: "odinnadtsat'", category: "numbers", example: { ru: "Поезд отходит в одиннадцать.", en: "The train departs at eleven." } },
  { id: "nu012", ru: "двенадцать", en: "twelve", translit: "dvenadtsat'", category: "numbers", example: { ru: "В полдень двенадцать часов.", en: "Noon is twelve o'clock." } },
  { id: "nu013", ru: "тринадцать", en: "thirteen", translit: "trinadtsat'", category: "numbers", example: { ru: "Ей тринадцать лет.", en: "She is thirteen years old." } },
  { id: "nu014", ru: "четырнадцать", en: "fourteen", translit: "chetyrnadtsat'", category: "numbers", example: { ru: "Ему четырнадцать лет.", en: "He is fourteen years old." } },
  { id: "nu015", ru: "пятнадцать", en: "fifteen", translit: "pyatnadtsat'", category: "numbers", example: { ru: "Я жду пятнадцать минут.", en: "I am waiting fifteen minutes." } },
  { id: "nu016", ru: "шестнадцать", en: "sixteen", translit: "shestnadtsat'", category: "numbers", example: { ru: "Ему шестнадцать лет.", en: "He is sixteen years old." } },
  { id: "nu017", ru: "семнадцать", en: "seventeen", translit: "semnadtsat'", category: "numbers", example: { ru: "Ей семнадцать лет.", en: "She is seventeen years old." } },
  { id: "nu018", ru: "восемнадцать", en: "eighteen", translit: "vosemnadtsat'", category: "numbers", example: { ru: "В восемнадцать лет можно голосовать.", en: "You can vote at eighteen." } },
  { id: "nu019", ru: "девятнадцать", en: "nineteen", translit: "devyatnadtsat'", category: "numbers", example: { ru: "Ему девятнадцать лет.", en: "He is nineteen years old." } },
  { id: "nu020", ru: "двадцать", en: "twenty", translit: "dvadtsat'", category: "numbers", example: { ru: "В группе двадцать студентов.", en: "There are twenty students in the group." } },
  { id: "nu021", ru: "двадцать один", en: "twenty-one", translit: "dvadtsat' odin", category: "numbers", example: { ru: "Мне двадцать один год.", en: "I am twenty-one years old." } },
  { id: "nu022", ru: "двадцать два", en: "twenty-two", translit: "dvadtsat' dva", category: "numbers", example: { ru: "У меня двадцать два рубля.", en: "I have twenty-two rubles." } },
  { id: "nu023", ru: "двадцать три", en: "twenty-three", translit: "dvadtsat' tri", category: "numbers", example: { ru: "В классе двадцать три студента.", en: "There are twenty-three students in the class." } },
  { id: "nu024", ru: "двадцать четыре", en: "twenty-four", translit: "dvadtsat' chetyre", category: "numbers", example: { ru: "В сутках двадцать четыре часа.", en: "There are twenty-four hours in a day." } },
  { id: "nu025", ru: "двадцать пять", en: "twenty-five", translit: "dvadtsat' pyat'", category: "numbers", example: { ru: "Билет стоит двадцать пять рублей.", en: "The ticket costs twenty-five rubles." } },
  { id: "nu026", ru: "двадцать шесть", en: "twenty-six", translit: "dvadtsat' shest'", category: "numbers", example: { ru: "Ей двадцать шесть лет.", en: "She is twenty-six years old." } },
  { id: "nu027", ru: "двадцать семь", en: "twenty-seven", translit: "dvadtsat' sem'", category: "numbers", example: { ru: "У нас двадцать семь книг.", en: "We have twenty-seven books." } },
  { id: "nu028", ru: "двадцать восемь", en: "twenty-eight", translit: "dvadtsat' vosem'", category: "numbers", example: { ru: "Автобус номер двадцать восемь.", en: "Bus number twenty-eight." } },
  { id: "nu029", ru: "двадцать девять", en: "twenty-nine", translit: "dvadtsat' devyat'", category: "numbers", example: { ru: "В группе двадцать девять человек.", en: "There are twenty-nine people in the group." } },
  { id: "nu030", ru: "тридцать", en: "thirty", translit: "tridtsat'", category: "numbers", example: { ru: "Мне тридцать лет.", en: "I am thirty years old." } },
  { id: "nu031", ru: "тридцать один", en: "thirty-one", translit: "tridtsat' odin", category: "numbers", example: { ru: "В месяце тридцать один день.", en: "There are thirty-one days in the month." } },
  { id: "nu032", ru: "тридцать два", en: "thirty-two", translit: "tridtsat' dva", category: "numbers", example: { ru: "У меня тридцать два письма.", en: "I have thirty-two letters." } },
  { id: "nu033", ru: "тридцать три", en: "thirty-three", translit: "tridtsat' tri", category: "numbers", example: { ru: "Он купил тридцать три открытки.", en: "He bought thirty-three postcards." } },
  { id: "nu034", ru: "тридцать четыре", en: "thirty-four", translit: "tridtsat' chetyre", category: "numbers", example: { ru: "В комнате тридцать четыре стула.", en: "There are thirty-four chairs in the room." } },
  { id: "nu035", ru: "тридцать пять", en: "thirty-five", translit: "tridtsat' pyat'", category: "numbers", example: { ru: "Поезд идёт тридцать пять минут.", en: "The train goes for thirty-five minutes." } },
  { id: "nu036", ru: "тридцать шесть", en: "thirty-six", translit: "tridtsat' shest'", category: "numbers", example: { ru: "На странице тридцать шесть слов.", en: "There are thirty-six words on the page." } },
  { id: "nu037", ru: "тридцать семь", en: "thirty-seven", translit: "tridtsat' sem'", category: "numbers", example: { ru: "Ему тридцать семь лет.", en: "He is thirty-seven years old." } },
  { id: "nu038", ru: "тридцать восемь", en: "thirty-eight", translit: "tridtsat' vosem'", category: "numbers", example: { ru: "У нас тридцать восемь заданий.", en: "We have thirty-eight tasks." } },
  { id: "nu039", ru: "тридцать девять", en: "thirty-nine", translit: "tridtsat' devyat'", category: "numbers", example: { ru: "Билет стоит тридцать девять рублей.", en: "The ticket costs thirty-nine rubles." } },
  { id: "nu040", ru: "сорок", en: "forty", translit: "sorok", category: "numbers", example: { ru: "Урок длится сорок минут.", en: "The lesson lasts forty minutes." } },
  { id: "nu041", ru: "сорок один", en: "forty-one", translit: "sorok odin", category: "numbers", example: { ru: "В списке сорок один студент.", en: "There are forty-one students on the list." } },
  { id: "nu042", ru: "сорок два", en: "forty-two", translit: "sorok dva", category: "numbers", example: { ru: "У неё сорок две фотографии.", en: "She has forty-two photos." } },
  { id: "nu043", ru: "сорок три", en: "forty-three", translit: "sorok tri", category: "numbers", example: { ru: "Мы прочитали сорок три страницы.", en: "We read forty-three pages." } },
  { id: "nu044", ru: "сорок четыре", en: "forty-four", translit: "sorok chetyre", category: "numbers", example: { ru: "Номер комнаты сорок четыре.", en: "The room number is forty-four." } },
  { id: "nu045", ru: "сорок пять", en: "forty-five", translit: "sorok pyat'", category: "numbers", example: { ru: "Мы ждём сорок пять минут.", en: "We are waiting forty-five minutes." } },
  { id: "nu046", ru: "сорок шесть", en: "forty-six", translit: "sorok shest'", category: "numbers", example: { ru: "В коробке сорок шесть карандашей.", en: "There are forty-six pencils in the box." } },
  { id: "nu047", ru: "сорок семь", en: "forty-seven", translit: "sorok sem'", category: "numbers", example: { ru: "Он написал сорок семь слов.", en: "He wrote forty-seven words." } },
  { id: "nu048", ru: "сорок восемь", en: "forty-eight", translit: "sorok vosem'", category: "numbers", example: { ru: "У нас сорок восемь часов.", en: "We have forty-eight hours." } },
  { id: "nu049", ru: "сорок девять", en: "forty-nine", translit: "sorok devyat'", category: "numbers", example: { ru: "На полке сорок девять книг.", en: "There are forty-nine books on the shelf." } },
  { id: "nu050", ru: "пятьдесят", en: "fifty", translit: "pyat'desyat", category: "numbers", example: { ru: "Это стоит пятьдесят рублей.", en: "It costs fifty rubles." } },
  { id: "nu051", ru: "пятьдесят один", en: "fifty-one", translit: "pyat'desyat odin", category: "numbers", example: { ru: "Автобус номер пятьдесят один.", en: "Bus number fifty-one." } },
  { id: "nu052", ru: "пятьдесят два", en: "fifty-two", translit: "pyat'desyat dva", category: "numbers", example: { ru: "В году пятьдесят две недели.", en: "There are fifty-two weeks in a year." } },
  { id: "nu053", ru: "пятьдесят три", en: "fifty-three", translit: "pyat'desyat tri", category: "numbers", example: { ru: "Он знает пятьдесят три слова.", en: "He knows fifty-three words." } },
  { id: "nu054", ru: "пятьдесят четыре", en: "fifty-four", translit: "pyat'desyat chetyre", category: "numbers", example: { ru: "В зале пятьдесят четыре места.", en: "There are fifty-four seats in the hall." } },
  { id: "nu055", ru: "пятьдесят пять", en: "fifty-five", translit: "pyat'desyat pyat'", category: "numbers", example: { ru: "Она пришла в пятьдесят пять минут.", en: "She arrived at fifty-five minutes past." } },
  { id: "nu056", ru: "пятьдесят шесть", en: "fifty-six", translit: "pyat'desyat shest'", category: "numbers", example: { ru: "У него пятьдесят шесть открыток.", en: "He has fifty-six postcards." } },
  { id: "nu057", ru: "пятьдесят семь", en: "fifty-seven", translit: "pyat'desyat sem'", category: "numbers", example: { ru: "Мы сделали пятьдесят семь упражнений.", en: "We did fifty-seven exercises." } },
  { id: "nu058", ru: "пятьдесят восемь", en: "fifty-eight", translit: "pyat'desyat vosem'", category: "numbers", example: { ru: "На столе пятьдесят восемь листов.", en: "There are fifty-eight sheets on the table." } },
  { id: "nu059", ru: "пятьдесят девять", en: "fifty-nine", translit: "pyat'desyat devyat'", category: "numbers", example: { ru: "Ей пятьдесят девять лет.", en: "She is fifty-nine years old." } },
  { id: "nu060", ru: "шестьдесят", en: "sixty", translit: "shest'desyat", category: "numbers", example: { ru: "В часе шестьдесят минут.", en: "There are sixty minutes in an hour." } },
  { id: "nu061", ru: "шестьдесят один", en: "sixty-one", translit: "shest'desyat odin", category: "numbers", example: { ru: "У нас шестьдесят один билет.", en: "We have sixty-one tickets." } },
  { id: "nu062", ru: "шестьдесят два", en: "sixty-two", translit: "shest'desyat dva", category: "numbers", example: { ru: "В списке шестьдесят два имени.", en: "There are sixty-two names on the list." } },
  { id: "nu063", ru: "шестьдесят три", en: "sixty-three", translit: "shest'desyat tri", category: "numbers", example: { ru: "Он прочитал шестьдесят три страницы.", en: "He read sixty-three pages." } },
  { id: "nu064", ru: "шестьдесят четыре", en: "sixty-four", translit: "shest'desyat chetyre", category: "numbers", example: { ru: "В комнате шестьдесят четыре места.", en: "There are sixty-four seats in the room." } },
  { id: "nu065", ru: "шестьдесят пять", en: "sixty-five", translit: "shest'desyat pyat'", category: "numbers", example: { ru: "Ему шестьдесят пять лет.", en: "He is sixty-five years old." } },
  { id: "nu066", ru: "шестьдесят шесть", en: "sixty-six", translit: "shest'desyat shest'", category: "numbers", example: { ru: "Мы повторили шестьдесят шесть слов.", en: "We reviewed sixty-six words." } },
  { id: "nu067", ru: "шестьдесят семь", en: "sixty-seven", translit: "shest'desyat sem'", category: "numbers", example: { ru: "У неё шестьдесят семь заметок.", en: "She has sixty-seven notes." } },
  { id: "nu068", ru: "шестьдесят восемь", en: "sixty-eight", translit: "shest'desyat vosem'", category: "numbers", example: { ru: "Билет стоит шестьдесят восемь рублей.", en: "The ticket costs sixty-eight rubles." } },
  { id: "nu069", ru: "шестьдесят девять", en: "sixty-nine", translit: "shest'desyat devyat'", category: "numbers", example: { ru: "На уроке шестьдесят девять примеров.", en: "There are sixty-nine examples in the lesson." } },
  { id: "nu070", ru: "семьдесят", en: "seventy", translit: "sem'desyat", category: "numbers", example: { ru: "В аудитории семьдесят стульев.", en: "There are seventy chairs in the classroom." } },
  { id: "nu071", ru: "семьдесят один", en: "seventy-one", translit: "sem'desyat odin", category: "numbers", example: { ru: "Он набрал семьдесят один балл.", en: "He scored seventy-one points." } },
  { id: "nu072", ru: "семьдесят два", en: "seventy-two", translit: "sem'desyat dva", category: "numbers", example: { ru: "У меня семьдесят два рубля.", en: "I have seventy-two rubles." } },
  { id: "nu073", ru: "семьдесят три", en: "seventy-three", translit: "sem'desyat tri", category: "numbers", example: { ru: "В файле семьдесят три строки.", en: "There are seventy-three lines in the file." } },
  { id: "nu074", ru: "семьдесят четыре", en: "seventy-four", translit: "sem'desyat chetyre", category: "numbers", example: { ru: "Мы сделали семьдесят четыре карточки.", en: "We made seventy-four cards." } },
  { id: "nu075", ru: "семьдесят пять", en: "seventy-five", translit: "sem'desyat pyat'", category: "numbers", example: { ru: "Скидка семьдесят пять процентов.", en: "The discount is seventy-five percent." } },
  { id: "nu076", ru: "семьдесят шесть", en: "seventy-six", translit: "sem'desyat shest'", category: "numbers", example: { ru: "На полке семьдесят шесть книг.", en: "There are seventy-six books on the shelf." } },
  { id: "nu077", ru: "семьдесят семь", en: "seventy-seven", translit: "sem'desyat sem'", category: "numbers", example: { ru: "Она знает семьдесят семь слов.", en: "She knows seventy-seven words." } },
  { id: "nu078", ru: "семьдесят восемь", en: "seventy-eight", translit: "sem'desyat vosem'", category: "numbers", example: { ru: "В пакете семьдесят восемь открыток.", en: "There are seventy-eight postcards in the bag." } },
  { id: "nu079", ru: "семьдесят девять", en: "seventy-nine", translit: "sem'desyat devyat'", category: "numbers", example: { ru: "У нас семьдесят девять ответов.", en: "We have seventy-nine answers." } },
  { id: "nu080", ru: "восемьдесят", en: "eighty", translit: "vosem'desyat", category: "numbers", example: { ru: "Дедушке восемьдесят лет.", en: "Grandfather is eighty years old." } },
  { id: "nu081", ru: "восемьдесят один", en: "eighty-one", translit: "vosem'desyat odin", category: "numbers", example: { ru: "В списке восемьдесят один адрес.", en: "There are eighty-one addresses on the list." } },
  { id: "nu082", ru: "восемьдесят два", en: "eighty-two", translit: "vosem'desyat dva", category: "numbers", example: { ru: "На столе восемьдесят две карточки.", en: "There are eighty-two cards on the table." } },
  { id: "nu083", ru: "восемьдесят три", en: "eighty-three", translit: "vosem'desyat tri", category: "numbers", example: { ru: "Мы выучили восемьдесят три слова.", en: "We learned eighty-three words." } },
  { id: "nu084", ru: "восемьдесят четыре", en: "eighty-four", translit: "vosem'desyat chetyre", category: "numbers", example: { ru: "У неё восемьдесят четыре письма.", en: "She has eighty-four letters." } },
  { id: "nu085", ru: "восемьдесят пять", en: "eighty-five", translit: "vosem'desyat pyat'", category: "numbers", example: { ru: "Цена восемьдесят пять рублей.", en: "The price is eighty-five rubles." } },
  { id: "nu086", ru: "восемьдесят шесть", en: "eighty-six", translit: "vosem'desyat shest'", category: "numbers", example: { ru: "Он сделал восемьдесят шесть упражнений.", en: "He did eighty-six exercises." } },
  { id: "nu087", ru: "восемьдесят семь", en: "eighty-seven", translit: "vosem'desyat sem'", category: "numbers", example: { ru: "На странице восемьдесят семь слов.", en: "There are eighty-seven words on the page." } },
  { id: "nu088", ru: "восемьдесят восемь", en: "eighty-eight", translit: "vosem'desyat vosem'", category: "numbers", example: { ru: "У нас восемьдесят восемь билетов.", en: "We have eighty-eight tickets." } },
  { id: "nu089", ru: "восемьдесят девять", en: "eighty-nine", translit: "vosem'desyat devyat'", category: "numbers", example: { ru: "В зале восемьдесят девять человек.", en: "There are eighty-nine people in the hall." } },
  { id: "nu090", ru: "девяносто", en: "ninety", translit: "devyanosto", category: "numbers", example: { ru: "Поезд идёт девяносто минут.", en: "The train goes for ninety minutes." } },
  { id: "nu091", ru: "девяносто один", en: "ninety-one", translit: "devyanosto odin", category: "numbers", example: { ru: "В таблице девяносто один номер.", en: "There are ninety-one numbers in the table." } },
  { id: "nu092", ru: "девяносто два", en: "ninety-two", translit: "devyanosto dva", category: "numbers", example: { ru: "У нас девяносто два вопроса.", en: "We have ninety-two questions." } },
  { id: "nu093", ru: "девяносто три", en: "ninety-three", translit: "devyanosto tri", category: "numbers", example: { ru: "Он прочитал девяносто три страницы.", en: "He read ninety-three pages." } },
  { id: "nu094", ru: "девяносто четыре", en: "ninety-four", translit: "devyanosto chetyre", category: "numbers", example: { ru: "В списке девяносто четыре слова.", en: "There are ninety-four words on the list." } },
  { id: "nu095", ru: "девяносто пять", en: "ninety-five", translit: "devyanosto pyat'", category: "numbers", example: { ru: "Результат девяносто пять процентов.", en: "The result is ninety-five percent." } },
  { id: "nu096", ru: "девяносто шесть", en: "ninety-six", translit: "devyanosto shest'", category: "numbers", example: { ru: "На уроке девяносто шесть примеров.", en: "There are ninety-six examples in the lesson." } },
  { id: "nu097", ru: "девяносто семь", en: "ninety-seven", translit: "devyanosto sem'", category: "numbers", example: { ru: "У него девяносто семь карточек.", en: "He has ninety-seven cards." } },
  { id: "nu098", ru: "девяносто восемь", en: "ninety-eight", translit: "devyanosto vosem'", category: "numbers", example: { ru: "Мы повторили девяносто восемь слов.", en: "We reviewed ninety-eight words." } },
  { id: "nu099", ru: "девяносто девять", en: "ninety-nine", translit: "devyanosto devyat'", category: "numbers", example: { ru: "На доске девяносто девять чисел.", en: "There are ninety-nine numbers on the board." } },
  { id: "nu100", ru: "сто", en: "one hundred", translit: "sto", category: "numbers", example: { ru: "Сто студентов пришли на урок.", en: "One hundred students came to the lesson." } },

  // Family (12)
  { id: "fm001", ru: "мама", en: "mom / mother", translit: "mama", category: "family", example: { ru: "Моя мама готовит вкусно.", en: "My mom cooks well." } },
  { id: "fm002", ru: "папа", en: "dad / father", translit: "papa", category: "family", example: { ru: "Папа читает газету.", en: "Dad is reading the newspaper." } },
  { id: "fm003", ru: "сестра", en: "sister", translit: "sestra", category: "family", example: { ru: "Моя сестра живёт в Москве.", en: "My sister lives in Moscow." } },
  { id: "fm004", ru: "брат", en: "brother", translit: "brat", category: "family", example: { ru: "Мой брат учится в университете.", en: "My brother studies at the university." } },
  { id: "fm005", ru: "бабушка", en: "grandmother", translit: "babushka", category: "family", example: { ru: "Бабушка любит пить чай.", en: "Grandmother likes to drink tea." } },
  { id: "fm006", ru: "дедушка", en: "grandfather", translit: "dedushka", category: "family", example: { ru: "Дедушка рассказывает истории.", en: "Grandfather tells stories." } },
  { id: "fm007", ru: "сын", en: "son", translit: "syn", category: "family", example: { ru: "Мой сын учится в школе.", en: "My son goes to school." } },
  { id: "fm008", ru: "дочь", en: "daughter", translit: "doch'", phonetic: "/ˈdɔːtər/", category: "family", example: { ru: "Дочь помогает маме.", en: "The daughter helps mom." } },
  { id: "fm009", ru: "муж", en: "husband", translit: "muzh", category: "family", example: { ru: "Мой муж работает врачом.", en: "My husband works as a doctor." } },
  { id: "fm010", ru: "жена", en: "wife", translit: "zhena", phonetic: "/waɪf/", category: "family", example: { ru: "Его жена говорит по-английски.", en: "His wife speaks English." } },
  { id: "fm011", ru: "друг", en: "friend (male)", translit: "drug", category: "family", example: { ru: "Мой друг живёт рядом.", en: "My friend lives nearby." } },
  { id: "fm012", ru: "подруга", en: "friend (female)", translit: "podruga", category: "family", example: { ru: "Моя подруга говорит по-английски.", en: "My female friend speaks English." } },

  // Food (15)
  { id: "fd001", ru: "хлеб", en: "bread", translit: "khleb", category: "food", example: { ru: "Я купил хлеб в магазине.", en: "I bought bread at the store." } },
  { id: "fd002", ru: "вода", en: "water", translit: "voda", phonetic: "/ˈwɔːtər/", category: "food", example: { ru: "Дайте мне воды, пожалуйста.", en: "Please give me some water." } },
  { id: "fd003", ru: "молоко", en: "milk", translit: "moloko", category: "food", example: { ru: "Дети пьют молоко каждый день.", en: "Children drink milk every day." } },
  { id: "fd004", ru: "чай", en: "tea", translit: "chay", category: "food", example: { ru: "Она пьёт чай с сахаром.", en: "She drinks tea with sugar." } },
  { id: "fd005", ru: "кофе", en: "coffee", translit: "kofe", category: "food", example: { ru: "Я пью кофе по утрам.", en: "I drink coffee in the mornings." } },
  { id: "fd006", ru: "яблоко", en: "apple", translit: "yabloko", category: "food", example: { ru: "Это красное яблоко очень вкусное.", en: "This red apple is very tasty." } },
  { id: "fd007", ru: "мясо", en: "meat", translit: "myaso", category: "food", example: { ru: "Он ест мясо каждый день.", en: "He eats meat every day." } },
  { id: "fd008", ru: "рыба", en: "fish", translit: "ryba", category: "food", example: { ru: "Рыба полезна для здоровья.", en: "Fish is good for your health." } },
  { id: "fd009", ru: "суп", en: "soup", translit: "sup", category: "food", example: { ru: "Мама варит суп на обед.", en: "Mom is making soup for lunch." } },
  { id: "fd010", ru: "салат", en: "salad", translit: "salat", category: "food", example: { ru: "Я заказал салат в ресторане.", en: "I ordered a salad at the restaurant." } },
  { id: "fd011", ru: "сыр", en: "cheese", translit: "syr", category: "food", example: { ru: "Он любит есть сыр с хлебом.", en: "He likes to eat cheese with bread." } },
  { id: "fd012", ru: "яйцо", en: "egg", translit: "yaytso", category: "food", example: { ru: "Я жарю яйцо на завтрак.", en: "I am frying an egg for breakfast." } },
  { id: "fd013", ru: "масло", en: "butter / oil", translit: "maslo", category: "food", example: { ru: "Положи масло на хлеб.", en: "Put butter on the bread." } },
  { id: "fd014", ru: "сахар", en: "sugar", translit: "sakhar", category: "food", example: { ru: "Ты хочешь сахар в чай?", en: "Do you want sugar in your tea?" } },
  { id: "fd015", ru: "соль", en: "salt", translit: "sol'", category: "food", example: { ru: "Добавь соль в суп.", en: "Add salt to the soup." } },

  // Places (12)
  { id: "pl001", ru: "дом", en: "house / home", translit: "dom", category: "places", example: { ru: "Я иду домой.", en: "I am going home." } },
  { id: "pl002", ru: "город", en: "city / town", translit: "gorod", category: "places", example: { ru: "Этот город очень большой.", en: "This city is very big." } },
  { id: "pl003", ru: "улица", en: "street", translit: "ulitsa", category: "places", example: { ru: "Магазин находится на этой улице.", en: "The store is on this street." } },
  { id: "pl004", ru: "магазин", en: "shop / store", translit: "magazin", category: "places", example: { ru: "Я иду в магазин за хлебом.", en: "I am going to the store for bread." } },
  { id: "pl005", ru: "школа", en: "school", translit: "shkola", category: "places", example: { ru: "Дети идут в школу.", en: "The children are going to school." } },
  { id: "pl006", ru: "работа", en: "work / job", translit: "rabota", phonetic: "/wɜːrk/", category: "places", example: { ru: "Он едет на работу на автобусе.", en: "He goes to work by bus." } },
  { id: "pl007", ru: "больница", en: "hospital", translit: "bol'nitsa", category: "places", example: { ru: "Врач работает в больнице.", en: "The doctor works at the hospital." } },
  { id: "pl008", ru: "аэропорт", en: "airport", translit: "aeroport", category: "places", example: { ru: "Такси едет в аэропорт.", en: "The taxi is going to the airport." } },
  { id: "pl009", ru: "ресторан", en: "restaurant", translit: "restoran", category: "places", example: { ru: "Мы ужинаем в ресторане.", en: "We are having dinner at the restaurant." } },
  { id: "pl010", ru: "гостиница", en: "hotel", translit: "gostinitsa", category: "places", example: { ru: "Я живу в гостинице.", en: "I am staying at the hotel." } },
  { id: "pl011", ru: "банк", en: "bank", translit: "bank", category: "places", example: { ru: "Банк открывается в девять часов.", en: "The bank opens at nine o'clock." } },
  { id: "pl012", ru: "парк", en: "park", translit: "park", category: "places", example: { ru: "Дети играют в парке.", en: "Children are playing in the park." } },

  // Essential verbs (20)
  { id: "vb001", ru: "быть", en: "to be", translit: "byt'", category: "verbs", example: { ru: "Я хочу быть врачом.", en: "I want to be a doctor." } },
  { id: "vb002", ru: "иметь", en: "to have", translit: "imet'", phonetic: "/hæv/", category: "verbs", example: { ru: "Я хочу иметь машину.", en: "I want to have a car." } },
  { id: "vb003", ru: "хотеть", en: "to want", translit: "khotet'", category: "verbs", example: { ru: "Я хочу пить воду.", en: "I want to drink water." } },
  { id: "vb004", ru: "идти", en: "to go (on foot)", translit: "idti", category: "verbs", example: { ru: "Я иду в магазин.", en: "I am going to the store." } },
  { id: "vb005", ru: "ехать", en: "to go (by vehicle)", translit: "yekhat'", category: "verbs", example: { ru: "Мы едем на автобусе.", en: "We are going by bus." } },
  { id: "vb006", ru: "говорить", en: "to speak / say", translit: "govorit'", category: "verbs", example: { ru: "Он говорит по-русски.", en: "He speaks Russian." } },
  { id: "vb007", ru: "знать", en: "to know", translit: "znat'", phonetic: "/noʊ/", category: "verbs", example: { ru: "Я знаю этот город.", en: "I know this city." } },
  { id: "vb008", ru: "видеть", en: "to see", translit: "videt'", category: "verbs", example: { ru: "Я вижу большой дом.", en: "I see a big house." } },
  { id: "vb009", ru: "слышать", en: "to hear", translit: "slyshat'", category: "verbs", example: { ru: "Я слышу музыку.", en: "I hear music." } },
  { id: "vb010", ru: "любить", en: "to love / like", translit: "lyubit'", category: "verbs", example: { ru: "Она любит читать книги.", en: "She loves to read books." } },
  { id: "vb011", ru: "делать", en: "to do / make", translit: "delat'", category: "verbs", example: { ru: "Что ты делаешь сейчас?", en: "What are you doing now?" } },
  { id: "vb012", ru: "работать", en: "to work", translit: "rabotat'", phonetic: "/wɜːrk/", category: "verbs", example: { ru: "Он работает каждый день.", en: "He works every day." } },
  { id: "vb013", ru: "жить", en: "to live", translit: "zhit'", phonetic: "/lɪv/", category: "verbs", example: { ru: "Я живу в Москве.", en: "I live in Moscow." } },
  { id: "vb014", ru: "есть", en: "to eat", translit: "yest'", category: "verbs", example: { ru: "Мы едим вместе.", en: "We eat together." } },
  { id: "vb015", ru: "пить", en: "to drink", translit: "pit'", category: "verbs", example: { ru: "Она пьёт кофе.", en: "She is drinking coffee." } },
  { id: "vb016", ru: "читать", en: "to read", translit: "chitat'", category: "verbs", example: { ru: "Я читаю книгу.", en: "I am reading a book." } },
  { id: "vb017", ru: "писать", en: "to write", translit: "pisat'", phonetic: "/raɪt/", category: "verbs", example: { ru: "Он пишет письмо.", en: "He is writing a letter." } },
  { id: "vb018", ru: "понимать", en: "to understand", translit: "ponimat'", category: "verbs", example: { ru: "Я понимаю по-русски.", en: "I understand Russian." } },
  { id: "vb019", ru: "думать", en: "to think", translit: "dumat'", phonetic: "/θɪŋk/", category: "verbs", example: { ru: "Я думаю об этом.", en: "I am thinking about this." } },
  { id: "vb020", ru: "купить", en: "to buy", translit: "kupit'", category: "verbs", example: { ru: "Я хочу купить хлеб.", en: "I want to buy bread." } },

  // Basic adjectives (15)
  { id: "aj001", ru: "большой", en: "big / large", translit: "bol'shoy", category: "adjectives", example: { ru: "Это большой город.", en: "This is a big city." } },
  { id: "aj002", ru: "маленький", en: "small / little", translit: "malen'kiy", category: "adjectives", example: { ru: "У меня маленькая комната.", en: "I have a small room." } },
  { id: "aj003", ru: "новый", en: "new", translit: "novyy", category: "adjectives", example: { ru: "Это мой новый телефон.", en: "This is my new phone." } },
  { id: "aj004", ru: "старый", en: "old", translit: "staryy", category: "adjectives", example: { ru: "Этот дом очень старый.", en: "This house is very old." } },
  { id: "aj005", ru: "красивый", en: "beautiful / pretty", translit: "krasivyy", category: "adjectives", example: { ru: "Это красивый парк.", en: "This is a beautiful park." } },
  { id: "aj006", ru: "плохой", en: "bad", translit: "plokhoy", phonetic: "/bæd/", category: "adjectives", example: { ru: "Сегодня плохая погода.", en: "The weather is bad today." } },
  { id: "aj007", ru: "быстрый", en: "fast / quick", translit: "bystryy", category: "adjectives", example: { ru: "Этот поезд очень быстрый.", en: "This train is very fast." } },
  { id: "aj008", ru: "медленный", en: "slow", translit: "medlennyy", category: "adjectives", example: { ru: "Этот автобус очень медленный.", en: "This bus is very slow." } },
  { id: "aj009", ru: "дорогой", en: "expensive / dear", translit: "dorogoy", category: "adjectives", example: { ru: "Этот ресторан очень дорогой.", en: "This restaurant is very expensive." } },
  { id: "aj010", ru: "дешёвый", en: "cheap / inexpensive", translit: "deshyovyy", category: "adjectives", example: { ru: "Этот магазин дешёвый.", en: "This store is cheap." } },
  { id: "aj011", ru: "горячий", en: "hot", translit: "goryachiy", category: "adjectives", example: { ru: "Чай ещё горячий.", en: "The tea is still hot." } },
  { id: "aj012", ru: "холодный", en: "cold", translit: "kholodnyy", category: "adjectives", example: { ru: "На улице холодный ветер.", en: "There is a cold wind outside." } },
  { id: "aj013", ru: "правый", en: "right (direction)", translit: "pravyy", category: "adjectives", example: { ru: "Поверни направо.", en: "Turn right." } },
  { id: "aj014", ru: "левый", en: "left (direction)", translit: "levyy", category: "adjectives", example: { ru: "Банк слева.", en: "The bank is on the left." } },
  { id: "aj015", ru: "трудный", en: "difficult / hard", translit: "trudnyy", category: "adjectives", example: { ru: "Это трудный экзамен.", en: "This is a difficult exam." } },

  // Days of the week (7)
  { id: "dy001", ru: "понедельник", en: "Monday", translit: "ponedel'nik", category: "days", example: { ru: "В понедельник я иду на работу.", en: "On Monday I go to work." } },
  { id: "dy002", ru: "вторник", en: "Tuesday", translit: "vtornik", category: "days", example: { ru: "Встреча во вторник.", en: "The meeting is on Tuesday." } },
  { id: "dy003", ru: "среда", en: "Wednesday", translit: "sreda", category: "days", example: { ru: "В среду я иду в магазин.", en: "On Wednesday I go to the store." } },
  { id: "dy004", ru: "четверг", en: "Thursday", translit: "chetverg", category: "days", example: { ru: "В четверг у нас урок.", en: "On Thursday we have a lesson." } },
  { id: "dy005", ru: "пятница", en: "Friday", translit: "pyatnitsa", category: "days", example: { ru: "В пятницу мы отдыхаем.", en: "On Friday we rest." } },
  { id: "dy006", ru: "суббота", en: "Saturday", translit: "subbota", category: "days", example: { ru: "В субботу я дома.", en: "On Saturday I am at home." } },
  { id: "dy007", ru: "воскресенье", en: "Sunday", translit: "voskresen'ye", category: "days", example: { ru: "В воскресенье мы идём в парк.", en: "On Sunday we go to the park." } },

  // Essential phrases (4)
  { id: "ph001", ru: "я не понимаю", en: "I don't understand", translit: "ya ne ponimayu", category: "phrases", example: { ru: "Я не понимаю — говорите медленнее.", en: "I don't understand — please speak slower." } },
  { id: "ph002", ru: "повторите, пожалуйста", en: "please repeat that", translit: "povtorite, pozhaluysta", category: "phrases", example: { ru: "Повторите, пожалуйста, я не слышал.", en: "Please repeat, I didn't hear." } },
  { id: "ph003", ru: "сколько стоит?", en: "how much does it cost?", translit: "skol'ko stoit?", category: "phrases", example: { ru: "Сколько стоит этот билет?", en: "How much does this ticket cost?" } },
  { id: "ph004", ru: "где находится...?", en: "where is...?", translit: "gde nakhoditsya...?", category: "phrases", example: { ru: "Где находится ближайший банк?", en: "Where is the nearest bank?" } },

  // Colors (15)
  { id: "cl001", ru: "красный", en: "red", translit: "krasnyy", category: "colors", example: { ru: "У неё красное платье.", en: "She has a red dress." } },
  { id: "cl002", ru: "синий", en: "blue", translit: "siniy", category: "colors", example: { ru: "Небо синее.", en: "The sky is blue." } },
  { id: "cl003", ru: "зелёный", en: "green", translit: "zelyonyy", category: "colors", example: { ru: "Трава зелёная весной.", en: "The grass is green in spring." } },
  { id: "cl004", ru: "жёлтый", en: "yellow", translit: "zhyoltyy", category: "colors", example: { ru: "Это жёлтый цветок.", en: "This is a yellow flower." } },
  { id: "cl005", ru: "чёрный", en: "black", translit: "chyornyy", phonetic: "/blæk/", category: "colors", example: { ru: "У него чёрная куртка.", en: "He has a black jacket." } },
  { id: "cl006", ru: "белый", en: "white", translit: "belyy", category: "colors", example: { ru: "Снег белый.", en: "Snow is white." } },
  { id: "cl007", ru: "оранжевый", en: "orange", translit: "oranzhevyy", category: "colors", example: { ru: "Апельсин оранжевый.", en: "An orange is orange." } },
  { id: "cl008", ru: "фиолетовый", en: "purple", translit: "fioletovyy", category: "colors", example: { ru: "Она любит фиолетовый цвет.", en: "She likes the color purple." } },
  { id: "cl009", ru: "розовый", en: "pink", translit: "rozovyy", category: "colors", example: { ru: "У девочки розовая шапка.", en: "The girl has a pink hat." } },
  { id: "cl010", ru: "серый", en: "grey", translit: "seryy", category: "colors", example: { ru: "Небо серое и облачное.", en: "The sky is grey and cloudy." } },
  { id: "cl011", ru: "коричневый", en: "brown", translit: "korichnevyy", category: "colors", example: { ru: "Стол коричневый.", en: "The table is brown." } },
  { id: "cl012", ru: "светлый", en: "light (color)", translit: "svetlyy", phonetic: "/laɪt/", category: "colors", example: { ru: "Она носит светлую рубашку.", en: "She wears a light-colored shirt." } },
  { id: "cl013", ru: "тёмный", en: "dark", translit: "tyomnyy", category: "colors", example: { ru: "Ночью очень темно.", en: "It is very dark at night." } },
  { id: "cl014", ru: "яркий", en: "bright", translit: "yarkiy", category: "colors", example: { ru: "Солнце сегодня яркое.", en: "The sun is bright today." } },
  { id: "cl015", ru: "бледный", en: "pale", translit: "blednyy", category: "colors", example: { ru: "Он выглядит бледным.", en: "He looks pale." } },

  // Body (20)
  { id: "bd001", ru: "голова", en: "head", translit: "golova", category: "body", example: { ru: "У меня болит голова.", en: "I have a headache." } },
  { id: "bd002", ru: "рука", en: "hand / arm", translit: "ruka", phonetic: "/hænd/", category: "body", example: { ru: "Она подняла руку.", en: "She raised her hand." } },
  { id: "bd003", ru: "глаз", en: "eye", translit: "glaz", category: "body", example: { ru: "У неё голубые глаза.", en: "She has blue eyes." } },
  { id: "bd004", ru: "ухо", en: "ear", translit: "ukho", category: "body", example: { ru: "У него болит ухо.", en: "His ear hurts." } },
  { id: "bd005", ru: "нос", en: "nose", translit: "nos", category: "body", example: { ru: "У неё красный нос.", en: "She has a red nose." } },
  { id: "bd006", ru: "рот", en: "mouth", translit: "rot", category: "body", example: { ru: "Открой рот.", en: "Open your mouth." } },
  { id: "bd007", ru: "стопа", en: "foot", translit: "stopa", category: "body", example: { ru: "У меня болит стопа.", en: "My foot hurts." } },
  { id: "bd008", ru: "нога", en: "leg", translit: "noga", category: "body", example: { ru: "Он сломал ногу.", en: "He broke his leg." } },
  { id: "bd009", ru: "спина", en: "back", translit: "spina", phonetic: "/bæk/", category: "body", example: { ru: "У меня болит спина.", en: "My back hurts." } },
  { id: "bd010", ru: "сердце", en: "heart", translit: "serdtse", category: "body", example: { ru: "Сердце бьётся быстро.", en: "The heart beats fast." } },
  { id: "bd011", ru: "живот", en: "stomach", translit: "zhivot", category: "body", example: { ru: "У меня болит живот.", en: "My stomach hurts." } },
  { id: "bd012", ru: "палец", en: "finger", translit: "palets", category: "body", example: { ru: "Он порезал палец.", en: "He cut his finger." } },
  { id: "bd013", ru: "лицо", en: "face", translit: "litso", category: "body", example: { ru: "Умой лицо.", en: "Wash your face." } },
  { id: "bd014", ru: "волосы", en: "hair", translit: "volosy", category: "body", example: { ru: "У неё длинные волосы.", en: "She has long hair." } },
  { id: "bd015", ru: "кожа", en: "skin", translit: "kozha", category: "body", example: { ru: "У неё мягкая кожа.", en: "She has soft skin." } },
  { id: "bd016", ru: "зуб", en: "tooth", translit: "zub", phonetic: "/tuːθ/", category: "body", example: { ru: "У меня болит зуб.", en: "I have a toothache." } },
  { id: "bd017", ru: "плечо", en: "shoulder", translit: "plecho", category: "body", example: { ru: "Он поднял плечо.", en: "He raised his shoulder." } },
  { id: "bd018", ru: "колено", en: "knee", translit: "koleno", category: "body", example: { ru: "Он упал на колено.", en: "He fell on his knee." } },
  { id: "bd019", ru: "грудь", en: "chest", translit: "grud'", category: "body", example: { ru: "Врач слушает грудь.", en: "The doctor is listening to the chest." } },
  { id: "bd020", ru: "шея", en: "neck", translit: "sheya", category: "body", example: { ru: "У меня болит шея.", en: "My neck hurts." } },

  // Clothing (15)
  { id: "ct001", ru: "рубашка", en: "shirt", translit: "rubashka", category: "clothing", example: { ru: "Он носит белую рубашку.", en: "He wears a white shirt." } },
  { id: "ct002", ru: "брюки", en: "pants", translit: "bryuki", category: "clothing", example: { ru: "Эти брюки слишком короткие.", en: "These pants are too short." } },
  { id: "ct003", ru: "платье", en: "dress", translit: "plat'ye", category: "clothing", example: { ru: "Она купила красивое платье.", en: "She bought a beautiful dress." } },
  { id: "ct004", ru: "туфли", en: "shoes", translit: "tufli", category: "clothing", example: { ru: "Её туфли очень удобные.", en: "Her shoes are very comfortable." } },
  { id: "ct005", ru: "пальто", en: "coat", translit: "pal'to", category: "clothing", example: { ru: "Надень пальто, на улице холодно.", en: "Put on your coat, it's cold outside." } },
  { id: "ct006", ru: "шапка", en: "hat", translit: "shapka", category: "clothing", example: { ru: "Где моя шапка?", en: "Where is my hat?" } },
  { id: "ct007", ru: "куртка", en: "jacket", translit: "kurtka", phonetic: "/ˈdʒækɪt/", category: "clothing", example: { ru: "Это новая куртка.", en: "This is a new jacket." } },
  { id: "ct008", ru: "носок", en: "sock", translit: "nosok", category: "clothing", example: { ru: "Я не могу найти носок.", en: "I cannot find my sock." } },
  { id: "ct009", ru: "сумка", en: "bag", translit: "sumka", phonetic: "/bæɡ/", category: "clothing", example: { ru: "Она несёт большую сумку.", en: "She is carrying a big bag." } },
  { id: "ct010", ru: "ремень", en: "belt", translit: "remen'", category: "clothing", example: { ru: "Он купил кожаный ремень.", en: "He bought a leather belt." } },
  { id: "ct011", ru: "шарф", en: "scarf", translit: "sharf", category: "clothing", example: { ru: "Она носит красный шарф.", en: "She wears a red scarf." } },
  { id: "ct012", ru: "перчатки", en: "gloves", translit: "perchatki", category: "clothing", example: { ru: "Зимой нужны перчатки.", en: "You need gloves in winter." } },
  { id: "ct013", ru: "юбка", en: "skirt", translit: "yubka", category: "clothing", example: { ru: "Она носит длинную юбку.", en: "She wears a long skirt." } },
  { id: "ct014", ru: "костюм", en: "suit", translit: "kostyum", category: "clothing", example: { ru: "Он надел костюм на собеседование.", en: "He wore a suit to the interview." } },
  { id: "ct015", ru: "галстук", en: "tie", translit: "galstuk", category: "clothing", example: { ru: "Папа надевает галстук на работу.", en: "Dad wears a tie to work." } },

  // Transport (12)
  { id: "tr001", ru: "машина", en: "car", translit: "mashina", category: "transport", example: { ru: "Моя машина в гараже.", en: "My car is in the garage." } },
  { id: "tr002", ru: "автобус", en: "bus", translit: "avtobus", category: "transport", example: { ru: "Автобус приходит каждые десять минут.", en: "The bus comes every ten minutes." } },
  { id: "tr003", ru: "поезд", en: "train", translit: "poyezd", category: "transport", example: { ru: "Поезд отходит в семь утра.", en: "The train departs at seven in the morning." } },
  { id: "tr004", ru: "самолёт", en: "plane", translit: "samolyot", category: "transport", example: { ru: "Самолёт летит в Москву.", en: "The plane is flying to Moscow." } },
  { id: "tr005", ru: "такси", en: "taxi", translit: "taksi", category: "transport", example: { ru: "Вызови такси, пожалуйста.", en: "Please call a taxi." } },
  { id: "tr006", ru: "велосипед", en: "bike", translit: "velosiped", category: "transport", example: { ru: "Он едет на велосипеде.", en: "He is riding a bike." } },
  { id: "tr007", ru: "метро", en: "metro / subway", translit: "metro", category: "transport", example: { ru: "Я еду на метро.", en: "I am going by metro." } },
  { id: "tr008", ru: "корабль", en: "ship", translit: "korabl'", phonetic: "/ʃɪp/", category: "transport", example: { ru: "Корабль плывёт в море.", en: "The ship is sailing at sea." } },
  { id: "tr009", ru: "идти пешком", en: "to walk", translit: "idti peshkom", category: "transport", example: { ru: "Я иду пешком до магазина.", en: "I am walking to the store." } },
  { id: "tr010", ru: "вести машину", en: "to drive", translit: "vesti mashinu", category: "transport", example: { ru: "Он ведёт машину осторожно.", en: "He drives carefully." } },
  { id: "tr011", ru: "лететь", en: "to fly", translit: "letet'", category: "transport", example: { ru: "Мы летим в Лондон.", en: "We are flying to London." } },
  { id: "tr012", ru: "билет", en: "ticket", translit: "bilet", category: "transport", example: { ru: "Я купил билет на поезд.", en: "I bought a train ticket." } },

  // Time (15)
  { id: "tm001", ru: "час", en: "hour", translit: "chas", phonetic: "/aʊər/", category: "time", example: { ru: "Я жду уже час.", en: "I have been waiting for an hour." } },
  { id: "tm002", ru: "минута", en: "minute", translit: "minuta", category: "time", example: { ru: "Подождите одну минуту.", en: "Wait one minute." } },
  { id: "tm003", ru: "секунда", en: "second", translit: "sekunda", category: "time", example: { ru: "Это заняло одну секунду.", en: "That took one second." } },
  { id: "tm004", ru: "сегодня", en: "today", translit: "segodnya", category: "time", example: { ru: "Сегодня хорошая погода.", en: "The weather is good today." } },
  { id: "tm005", ru: "завтра", en: "tomorrow", translit: "zavtra", category: "time", example: { ru: "Завтра у меня экзамен.", en: "I have an exam tomorrow." } },
  { id: "tm006", ru: "вчера", en: "yesterday", translit: "vchera", category: "time", example: { ru: "Вчера мы ходили в ресторан.", en: "Yesterday we went to a restaurant." } },
  { id: "tm007", ru: "утро", en: "morning", translit: "utro", category: "time", example: { ru: "Я встаю рано утром.", en: "I wake up early in the morning." } },
  { id: "tm008", ru: "день", en: "afternoon / daytime", translit: "den'", category: "time", example: { ru: "Днём я работаю.", en: "In the afternoon I work." } },
  { id: "tm009", ru: "вечер", en: "evening", translit: "vecher", category: "time", example: { ru: "Вечером мы смотрим телевизор.", en: "In the evening we watch TV." } },
  { id: "tm010", ru: "ночь", en: "night", translit: "noch'", phonetic: "/naɪt/", category: "time", example: { ru: "Ночью очень тихо.", en: "It is very quiet at night." } },
  { id: "tm011", ru: "неделя", en: "week", translit: "nedelya", phonetic: "/wiːk/", category: "time", example: { ru: "В неделе семь дней.", en: "There are seven days in a week." } },
  { id: "tm012", ru: "месяц", en: "month", translit: "mesyats", category: "time", example: { ru: "Я здесь уже месяц.", en: "I have been here for a month." } },
  { id: "tm013", ru: "год", en: "year", translit: "god", category: "time", example: { ru: "В году двенадцать месяцев.", en: "There are twelve months in a year." } },
  { id: "tm014", ru: "сейчас", en: "now", translit: "seychas", category: "time", example: { ru: "Что ты делаешь сейчас?", en: "What are you doing now?" } },
  { id: "tm015", ru: "потом", en: "later", translit: "potom", category: "time", example: { ru: "Поговорим об этом потом.", en: "Let's talk about this later." } },

  // Weather (12)
  { id: "wt001", ru: "солнце", en: "sun", translit: "solntse", category: "weather", example: { ru: "Сегодня светит солнце.", en: "The sun is shining today." } },
  { id: "wt002", ru: "дождь", en: "rain", translit: "dozhd'", category: "weather", example: { ru: "Идёт дождь.", en: "It is raining." } },
  { id: "wt003", ru: "снег", en: "snow", translit: "sneg", category: "weather", example: { ru: "Зимой идёт снег.", en: "It snows in winter." } },
  { id: "wt004", ru: "ветер", en: "wind", translit: "veter", phonetic: "/wɪnd/", category: "weather", example: { ru: "Сегодня сильный ветер.", en: "There is a strong wind today." } },
  { id: "wt005", ru: "жарко", en: "hot (weather)", translit: "zharko", category: "weather", example: { ru: "Летом очень жарко.", en: "It is very hot in summer." } },
  { id: "wt006", ru: "холодно", en: "cold (weather)", translit: "kholodno", category: "weather", example: { ru: "Зимой холодно.", en: "It is cold in winter." } },
  { id: "wt007", ru: "тепло", en: "warm (weather)", translit: "teplo", phonetic: "/wɔːrm/", category: "weather", example: { ru: "Весной тепло.", en: "It is warm in spring." } },
  { id: "wt008", ru: "облако", en: "cloud", translit: "oblako", category: "weather", example: { ru: "На небе много облаков.", en: "There are many clouds in the sky." } },
  { id: "wt009", ru: "гроза", en: "storm", translit: "groza", category: "weather", example: { ru: "Будет гроза.", en: "There will be a storm." } },
  { id: "wt010", ru: "туман", en: "fog", translit: "tuman", category: "weather", example: { ru: "Утром был туман.", en: "There was fog in the morning." } },
  { id: "wt011", ru: "температура", en: "temperature", translit: "temperatura", category: "weather", example: { ru: "Температура сегодня — двадцать градусов.", en: "The temperature today is twenty degrees." } },
  { id: "wt012", ru: "прогноз погоды", en: "weather forecast", translit: "prognoz pogody", category: "weather", example: { ru: "Прогноз погоды на завтра.", en: "The weather forecast for tomorrow." } },

  // Emotions (15)
  { id: "em001", ru: "счастливый", en: "happy", translit: "schastlivyy", category: "emotions", example: { ru: "Она очень счастливая.", en: "She is very happy." } },
  { id: "em002", ru: "грустный", en: "sad", translit: "grustnyy", category: "emotions", example: { ru: "Почему ты грустный?", en: "Why are you sad?" } },
  { id: "em003", ru: "злой", en: "angry", translit: "zloy", category: "emotions", example: { ru: "Он был очень злой.", en: "He was very angry." } },
  { id: "em004", ru: "испуганный", en: "scared", translit: "ispugannyy", category: "emotions", example: { ru: "Ребёнок был испуган.", en: "The child was scared." } },
  { id: "em005", ru: "удивлённый", en: "surprised", translit: "udivlyonnyy", category: "emotions", example: { ru: "Я был удивлён.", en: "I was surprised." } },
  { id: "em006", ru: "усталый", en: "tired", translit: "ustalyy", category: "emotions", example: { ru: "Я очень устал сегодня.", en: "I am very tired today." } },
  { id: "em007", ru: "скучающий", en: "bored", translit: "skuchayushchiy", category: "emotions", example: { ru: "Ему скучно дома.", en: "He is bored at home." } },
  { id: "em008", ru: "взволнованный", en: "excited", translit: "vzvolnovannyy", category: "emotions", example: { ru: "Она взволнована перед концертом.", en: "She is excited before the concert." } },
  { id: "em009", ru: "нервный", en: "nervous", translit: "nervnyy", category: "emotions", example: { ru: "Он нервный перед экзаменом.", en: "He is nervous before the exam." } },
  { id: "em010", ru: "гордый", en: "proud", translit: "gordyy", category: "emotions", example: { ru: "Мама гордая своим сыном.", en: "Mom is proud of her son." } },
  { id: "em011", ru: "смущённый", en: "embarrassed", translit: "smushchyonnyy", category: "emotions", example: { ru: "Он смутился.", en: "He was embarrassed." } },
  { id: "em012", ru: "одинокий", en: "lonely", translit: "odinokiy", category: "emotions", example: { ru: "Она чувствует себя одинокой.", en: "She feels lonely." } },
  { id: "em013", ru: "благодарный", en: "grateful", translit: "blagodarnyy", category: "emotions", example: { ru: "Я очень благодарен за помощь.", en: "I am very grateful for the help." } },
  { id: "em014", ru: "растерянный", en: "confused", translit: "rasteryanyy", category: "emotions", example: { ru: "Он выглядит растерянным.", en: "He looks confused." } },
  { id: "em015", ru: "спокойный", en: "calm", translit: "spokoynyy", category: "emotions", example: { ru: "Она остаётся спокойной.", en: "She stays calm." } },

  // Work (15)
  { id: "wk001", ru: "работа", en: "job / work", translit: "rabota", phonetic: "/wɜːrk/", category: "work", example: { ru: "Мне нравится моя работа.", en: "I like my job." } },
  { id: "wk002", ru: "офис", en: "office", translit: "ofis", category: "work", example: { ru: "Я работаю в офисе.", en: "I work in an office." } },
  { id: "wk003", ru: "встреча", en: "meeting", translit: "vstrecha", category: "work", example: { ru: "Встреча начинается в десять.", en: "The meeting starts at ten." } },
  { id: "wk004", ru: "компьютер", en: "computer", translit: "komp'yuter", category: "work", example: { ru: "Я работаю на компьютере.", en: "I work on a computer." } },
  { id: "wk005", ru: "телефон", en: "phone", translit: "telefon", category: "work", example: { ru: "Мой телефон звонит.", en: "My phone is ringing." } },
  { id: "wk006", ru: "электронная почта", en: "email", translit: "elektronnaya pochta", category: "work", example: { ru: "Я отправил письмо по электронной почте.", en: "I sent a letter by email." } },
  { id: "wk007", ru: "начальник", en: "boss", translit: "nachal'nik", category: "work", example: { ru: "Начальник доволен работой.", en: "The boss is happy with the work." } },
  { id: "wk008", ru: "коллега", en: "colleague", translit: "kollega", category: "work", example: { ru: "Мой коллега очень умный.", en: "My colleague is very smart." } },
  { id: "wk009", ru: "зарплата", en: "salary", translit: "zarplata", category: "work", example: { ru: "Зарплата приходит в конце месяца.", en: "The salary comes at the end of the month." } },
  { id: "wk010", ru: "проект", en: "project", translit: "proyekt", category: "work", example: { ru: "Мы работаем над новым проектом.", en: "We are working on a new project." } },
  { id: "wk011", ru: "дедлайн", en: "deadline", translit: "dedlayn", category: "work", example: { ru: "Дедлайн — в пятницу.", en: "The deadline is on Friday." } },
  { id: "wk012", ru: "собеседование", en: "interview", translit: "sobesedovaniye", category: "work", example: { ru: "Завтра у меня собеседование.", en: "I have an interview tomorrow." } },
  { id: "wk013", ru: "резюме", en: "resume / CV", translit: "rezyume", category: "work", example: { ru: "Я написал резюме.", en: "I wrote my resume." } },
  { id: "wk014", ru: "компания", en: "company", translit: "kompaniya", category: "work", example: { ru: "Это большая компания.", en: "This is a big company." } },
  { id: "wk015", ru: "контракт", en: "contract", translit: "kontrakt", category: "work", example: { ru: "Я подписал контракт.", en: "I signed the contract." } },

  // Health (15)
  { id: "hl001", ru: "врач", en: "doctor", translit: "vrach", category: "health", example: { ru: "Мне нужен врач.", en: "I need a doctor." } },
  { id: "hl002", ru: "больница", en: "hospital building", translit: "bol'nitsa", category: "health", example: { ru: "Его отвезли в больницу.", en: "He was taken to the hospital building." } },
  { id: "hl003", ru: "лекарство", en: "medicine", translit: "lekarstvo", category: "health", example: { ru: "Принимайте лекарство три раза в день.", en: "Take the medicine three times a day." } },
  { id: "hl004", ru: "боль", en: "pain", translit: "bol'", category: "health", example: { ru: "У меня сильная боль.", en: "I have a strong pain." } },
  { id: "hl005", ru: "температура", en: "fever", translit: "temperatura", category: "health", example: { ru: "У него высокая температура.", en: "He has a high fever." } },
  { id: "hl006", ru: "кашель", en: "cough", translit: "kashel'", category: "health", example: { ru: "У меня сильный кашель.", en: "I have a bad cough." } },
  { id: "hl007", ru: "головная боль", en: "headache", translit: "golovnaya bol'", category: "health", example: { ru: "У меня головная боль.", en: "I have a headache." } },
  { id: "hl008", ru: "аллергия", en: "allergy", translit: "allergiya", category: "health", example: { ru: "У меня аллергия на кошек.", en: "I am allergic to cats." } },
  { id: "hl009", ru: "рецепт", en: "prescription", translit: "retsept", category: "health", example: { ru: "Врач выписал рецепт.", en: "The doctor wrote a prescription." } },
  { id: "hl010", ru: "приём у врача", en: "appointment", translit: "priyom u vracha", category: "health", example: { ru: "У меня приём у врача в три часа.", en: "I have a doctor's appointment at three." } },
  { id: "hl011", ru: "аптека", en: "pharmacy", translit: "apteka", category: "health", example: { ru: "Аптека рядом с больницей.", en: "The pharmacy is near the hospital." } },
  { id: "hl012", ru: "больной", en: "sick", translit: "bol'noy", category: "health", example: { ru: "Он заболел и лежит дома.", en: "He is sick and staying home." } },
  { id: "hl013", ru: "здоровый", en: "healthy", translit: "zdorovyy", category: "health", example: { ru: "Она ведёт здоровый образ жизни.", en: "She leads a healthy lifestyle." } },
  { id: "hl014", ru: "сон", en: "sleep", translit: "son", category: "health", example: { ru: "Хороший сон важен для здоровья.", en: "Good sleep is important for health." } },
  { id: "hl015", ru: "отдых", en: "rest", translit: "otdykh", category: "health", example: { ru: "После работы мне нужен отдых.", en: "After work I need rest." } },

  // Education (15)
  { id: "ed001", ru: "школа", en: "school institution", translit: "shkola", category: "education", example: { ru: "Дети идут в школу каждый день.", en: "Children go to the school institution every day." } },
  { id: "ed002", ru: "университет", en: "university", translit: "universitet", category: "education", example: { ru: "Я учусь в университете.", en: "I study at the university." } },
  { id: "ed003", ru: "студент", en: "student", translit: "student", category: "education", example: { ru: "Он хороший студент.", en: "He is a good student." } },
  { id: "ed004", ru: "учитель", en: "teacher", translit: "uchitel'", category: "education", example: { ru: "Учитель объясняет урок.", en: "The teacher explains the lesson." } },
  { id: "ed005", ru: "урок", en: "lesson", translit: "urok", category: "education", example: { ru: "Урок начинается в восемь.", en: "The lesson starts at eight." } },
  { id: "ed006", ru: "домашнее задание", en: "homework", translit: "domashneye zadaniye", category: "education", example: { ru: "Я сделал домашнее задание.", en: "I did my homework." } },
  { id: "ed007", ru: "экзамен", en: "exam", translit: "ekzamen", category: "education", example: { ru: "Завтра у меня сложный экзамен.", en: "I have a difficult exam tomorrow." } },
  { id: "ed008", ru: "оценка", en: "grade / mark", translit: "otsenka", category: "education", example: { ru: "Он получил хорошую оценку.", en: "He got a good grade." } },
  { id: "ed009", ru: "книга", en: "book", translit: "kniga", category: "education", example: { ru: "Я читаю интересную книгу.", en: "I am reading an interesting book." } },
  { id: "ed010", ru: "библиотека", en: "library", translit: "biblioteka", category: "education", example: { ru: "Я беру книги в библиотеке.", en: "I borrow books from the library." } },
  { id: "ed011", ru: "класс", en: "class / classroom", translit: "klass", category: "education", example: { ru: "В классе двадцать учеников.", en: "There are twenty pupils in the class." } },
  { id: "ed012", ru: "предмет", en: "subject", translit: "predmet", category: "education", example: { ru: "Мой любимый предмет — математика.", en: "My favourite subject is mathematics." } },
  { id: "ed013", ru: "учиться", en: "to study", translit: "uchit'sya", category: "education", example: { ru: "Я учусь каждый день.", en: "I study every day." } },
  { id: "ed014", ru: "изучать", en: "to learn", translit: "izuchat'", category: "education", example: { ru: "Я изучаю русский язык.", en: "I am learning Russian." } },
  { id: "ed015", ru: "окончить", en: "to graduate", translit: "okonchit'", category: "education", example: { ru: "Она окончила университет.", en: "She graduated from university." } },

  // Shopping (12)
  { id: "sh001", ru: "магазин", en: "store / shop", translit: "magazin", category: "shopping", example: { ru: "Я иду в магазин.", en: "I am going to the store." } },
  { id: "sh002", ru: "цена", en: "price", translit: "tsena", category: "shopping", example: { ru: "Какая цена этого товара?", en: "What is the price of this item?" } },
  { id: "sh003", ru: "покупать", en: "to shop for", translit: "pokupat'", category: "shopping", example: { ru: "Я покупаю продукты каждую неделю.", en: "I shop for groceries every week." } },
  { id: "sh004", ru: "продавать", en: "to sell", translit: "prodavat'", category: "shopping", example: { ru: "Они продают свежие овощи.", en: "They sell fresh vegetables." } },
  { id: "sh005", ru: "дорогой", en: "expensive", translit: "dorogoy", category: "shopping", example: { ru: "Этот телефон очень дорогой.", en: "This phone is very expensive." } },
  { id: "sh006", ru: "дешёвый", en: "cheap", translit: "deshyovyy", category: "shopping", example: { ru: "Здесь цены дешёвые.", en: "The prices here are cheap." } },
  { id: "sh007", ru: "чек", en: "receipt", translit: "chek", category: "shopping", example: { ru: "Дайте мне чек, пожалуйста.", en: "Please give me the receipt." } },
  { id: "sh008", ru: "наличные", en: "cash", translit: "nalichnyye", category: "shopping", example: { ru: "Я плачу наличными.", en: "I pay with cash." } },
  { id: "sh009", ru: "карта", en: "card", translit: "karta", category: "shopping", example: { ru: "Можно платить картой?", en: "Can I pay by card?" } },
  { id: "sh010", ru: "скидка", en: "discount", translit: "skidka", category: "shopping", example: { ru: "На этот товар скидка десять процентов.", en: "There is a ten percent discount on this item." } },
  { id: "sh011", ru: "размер", en: "size", translit: "razmer", category: "shopping", example: { ru: "Какой у вас размер?", en: "What is your size?" } },
  { id: "sh012", ru: "сдача", en: "change (money)", translit: "sdacha", category: "shopping", example: { ru: "Вот ваша сдача.", en: "Here is your change." } },

  // Home (20)
  { id: "hm001", ru: "комната", en: "room", translit: "komnata", category: "home", example: { ru: "В квартире три комнаты.", en: "The apartment has three rooms." } },
  { id: "hm002", ru: "кухня", en: "kitchen", translit: "kukhnya", category: "home", example: { ru: "Мама готовит на кухне.", en: "Mom is cooking in the kitchen." } },
  { id: "hm003", ru: "спальня", en: "bedroom", translit: "spal'nya", category: "home", example: { ru: "Спальня на втором этаже.", en: "The bedroom is on the second floor." } },
  { id: "hm004", ru: "ванная", en: "bathroom", translit: "vannaya", category: "home", example: { ru: "Ванная комната слева.", en: "The bathroom is on the left." } },
  { id: "hm005", ru: "дверь", en: "door", translit: "dver'", category: "home", example: { ru: "Закройте дверь.", en: "Close the door." } },
  { id: "hm006", ru: "окно", en: "window", translit: "okno", phonetic: "/ˈwɪndoʊ/", category: "home", example: { ru: "Открой окно, здесь жарко.", en: "Open the window, it is hot here." } },
  { id: "hm007", ru: "стол", en: "table", translit: "stol", category: "home", example: { ru: "Книга лежит на столе.", en: "The book is on the table." } },
  { id: "hm008", ru: "стул", en: "chair", translit: "stul", category: "home", example: { ru: "Сядь на стул.", en: "Sit on the chair." } },
  { id: "hm009", ru: "кровать", en: "bed", translit: "krovat'", category: "home", example: { ru: "Она лежит в кровати.", en: "She is lying in bed." } },
  { id: "hm010", ru: "диван", en: "sofa", translit: "divan", category: "home", example: { ru: "Кот спит на диване.", en: "The cat is sleeping on the sofa." } },
  { id: "hm011", ru: "пол", en: "floor", translit: "pol", category: "home", example: { ru: "Помой пол.", en: "Wash the floor." } },
  { id: "hm012", ru: "стена", en: "wall", translit: "stena", phonetic: "/wɔːl/", category: "home", example: { ru: "На стене висит картина.", en: "A picture hangs on the wall." } },
  { id: "hm013", ru: "потолок", en: "ceiling", translit: "potolok", category: "home", example: { ru: "Потолок очень высокий.", en: "The ceiling is very high." } },
  { id: "hm014", ru: "лампа", en: "lamp", translit: "lampa", category: "home", example: { ru: "Включи лампу, темно.", en: "Turn on the lamp, it is dark." } },
  { id: "hm015", ru: "ключ", en: "key", translit: "klyuch", category: "home", example: { ru: "Я потерял ключ от дома.", en: "I lost the house key." } },
  { id: "hm016", ru: "сад", en: "garden", translit: "sad", category: "home", example: { ru: "Бабушка работает в саду.", en: "Grandmother is working in the garden." } },
  { id: "hm017", ru: "лестница", en: "stairs", translit: "lesnitsa", category: "home", example: { ru: "Поднимись по лестнице.", en: "Go up the stairs." } },
  { id: "hm018", ru: "полка", en: "shelf", translit: "polka", category: "home", example: { ru: "Книги стоят на полке.", en: "The books are on the shelf." } },
  { id: "hm019", ru: "зеркало", en: "mirror", translit: "zerkalo", category: "home", example: { ru: "Она смотрится в зеркало.", en: "She is looking in the mirror." } },
  { id: "hm020", ru: "полотенце", en: "towel", translit: "polotentse", category: "home", example: { ru: "Возьми полотенце.", en: "Take a towel." } },

  // Nature (15)
  { id: "nt001", ru: "дерево", en: "tree", translit: "derevo", category: "nature", example: { ru: "В парке много деревьев.", en: "There are many trees in the park." } },
  { id: "nt002", ru: "цветок", en: "flower", translit: "tsvetok", category: "nature", example: { ru: "Она купила красивые цветы.", en: "She bought beautiful flowers." } },
  { id: "nt003", ru: "река", en: "river", translit: "reka", category: "nature", example: { ru: "Мы купаемся в реке.", en: "We are swimming in the river." } },
  { id: "nt004", ru: "гора", en: "mountain", translit: "gora", category: "nature", example: { ru: "Гора очень высокая.", en: "The mountain is very high." } },
  { id: "nt005", ru: "море", en: "sea", translit: "more", category: "nature", example: { ru: "Летом мы едем на море.", en: "In summer we go to the sea." } },
  { id: "nt006", ru: "лес", en: "forest", translit: "les", category: "nature", example: { ru: "В лесу много грибов.", en: "There are many mushrooms in the forest." } },
  { id: "nt007", ru: "трава", en: "grass", translit: "trava", category: "nature", example: { ru: "Трава зелёная после дождя.", en: "The grass is green after rain." } },
  { id: "nt008", ru: "животное", en: "animal", translit: "zhivotnoye", category: "nature", example: { ru: "В зоопарке много животных.", en: "There are many animals in the zoo." } },
  { id: "nt009", ru: "птица", en: "bird", translit: "ptitsa", category: "nature", example: { ru: "Птица сидит на дереве.", en: "The bird is sitting on the tree." } },
  { id: "nt010", ru: "рыба", en: "river fish", translit: "ryba", category: "nature", example: { ru: "В реке плавает рыба.", en: "River fish swim in the river." } },
  { id: "nt011", ru: "собака", en: "dog", translit: "sobaka", category: "nature", example: { ru: "Собака бежит в парке.", en: "The dog is running in the park." } },
  { id: "nt012", ru: "кошка", en: "cat", translit: "koshka", phonetic: "/kæt/", category: "nature", example: { ru: "Кошка спит на диване.", en: "The cat is sleeping on the sofa." } },
  { id: "nt013", ru: "небо", en: "sky", translit: "nebo", category: "nature", example: { ru: "Небо сегодня голубое.", en: "The sky is blue today." } },
  { id: "nt014", ru: "земля", en: "earth / ground", translit: "zemlya", phonetic: "/ɜːrθ/", category: "nature", example: { ru: "Земля мокрая после дождя.", en: "The ground is wet after rain." } },
  { id: "nt015", ru: "камень", en: "stone", translit: "kamen'", category: "nature", example: { ru: "Он бросил камень в воду.", en: "He threw a stone into the water." } },

  // Common verbs 2 (20)
  { id: "vx001", ru: "приходить", en: "to come", translit: "prikhodit'", category: "verbs2", example: { ru: "Он приходит домой в шесть.", en: "He comes home at six." } },
  { id: "vx002", ru: "уходить", en: "to leave / go away", translit: "ukhodit'", phonetic: "/liːv/", category: "verbs2", example: { ru: "Она уходит на работу рано.", en: "She leaves for work early." } },
  { id: "vx003", ru: "давать", en: "to give", translit: "davat'", category: "verbs2", example: { ru: "Дай мне книгу.", en: "Give me the book." } },
  { id: "vx004", ru: "брать", en: "to take", translit: "brat'", category: "verbs2", example: { ru: "Возьми зонт, идёт дождь.", en: "Take an umbrella, it is raining." } },
  { id: "vx005", ru: "приносить", en: "to bring", translit: "prinosit'", category: "verbs2", example: { ru: "Принеси мне стакан воды.", en: "Bring me a glass of water." } },
  { id: "vx006", ru: "находить", en: "to find", translit: "nakhodit'", category: "verbs2", example: { ru: "Я не могу найти ключи.", en: "I cannot find my keys." } },
  { id: "vx007", ru: "терять", en: "to lose", translit: "teryat'", category: "verbs2", example: { ru: "Он часто теряет телефон.", en: "He often loses his phone." } },
  { id: "vx008", ru: "открывать", en: "to open", translit: "otkryvat'", category: "verbs2", example: { ru: "Открой дверь.", en: "Open the door." } },
  { id: "vx009", ru: "закрывать", en: "to close", translit: "zakryvat'", category: "verbs2", example: { ru: "Закрой окно.", en: "Close the window." } },
  { id: "vx010", ru: "начинать", en: "to start", translit: "nachinat'", category: "verbs2", example: { ru: "Урок начинается в девять.", en: "The lesson starts at nine." } },
  { id: "vx011", ru: "заканчивать", en: "to finish", translit: "zakanchivat'", category: "verbs2", example: { ru: "Я заканчиваю работу в пять.", en: "I finish work at five." } },
  { id: "vx012", ru: "пробовать", en: "to try", translit: "probovat'", category: "verbs2", example: { ru: "Попробуй это блюдо.", en: "Try this dish." } },
  { id: "vx013", ru: "помогать", en: "to help", translit: "pomogat'", category: "verbs2", example: { ru: "Он помогает маме.", en: "He helps mom." } },
  { id: "vx014", ru: "спрашивать", en: "to ask", translit: "sprashivat'", category: "verbs2", example: { ru: "Она спрашивает дорогу.", en: "She is asking for directions." } },
  { id: "vx015", ru: "рассказывать", en: "to tell", translit: "rasskazyvat'", category: "verbs2", example: { ru: "Расскажи мне о себе.", en: "Tell me about yourself." } },
  { id: "vx016", ru: "показывать", en: "to show", translit: "pokazyvat'", category: "verbs2", example: { ru: "Покажи мне карту.", en: "Show me the map." } },
  { id: "vx017", ru: "платить", en: "to pay", translit: "platit'", category: "verbs2", example: { ru: "Я плачу за обед.", en: "I am paying for lunch." } },
  { id: "vx018", ru: "звонить", en: "to call", translit: "zvonit'", category: "verbs2", example: { ru: "Позвони мне вечером.", en: "Call me in the evening." } },
  { id: "vx019", ru: "ждать", en: "to wait", translit: "zhdat'", category: "verbs2", example: { ru: "Жди меня здесь.", en: "Wait for me here." } },
  { id: "vx020", ru: "использовать", en: "to use", translit: "ispol'zovat'", category: "verbs2", example: { ru: "Используй словарь.", en: "Use the dictionary." } },

  // Adjectives 2 (15)
  { id: "ax001", ru: "высокий", en: "tall / high", translit: "vysokiy", category: "adjectives2", example: { ru: "Он очень высокий.", en: "He is very tall." } },
  { id: "ax002", ru: "низкий", en: "short / low", translit: "nizkiy", category: "adjectives2", example: { ru: "Этот стол низкий.", en: "This table is low." } },
  { id: "ax003", ru: "длинный", en: "long", translit: "dlinnyy", category: "adjectives2", example: { ru: "У неё длинные волосы.", en: "She has long hair." } },
  { id: "ax004", ru: "широкий", en: "wide", translit: "shirokiy", category: "adjectives2", example: { ru: "Улица очень широкая.", en: "The street is very wide." } },
  { id: "ax005", ru: "узкий", en: "narrow", translit: "uzkiy", category: "adjectives2", example: { ru: "Этот коридор узкий.", en: "This corridor is narrow." } },
  { id: "ax006", ru: "тяжёлый", en: "heavy", translit: "tyazholyy", category: "adjectives2", example: { ru: "Сумка очень тяжёлая.", en: "The bag is very heavy." } },
  { id: "ax007", ru: "лёгкий", en: "light (weight)", translit: "lyogkiy", category: "adjectives2", example: { ru: "Этот чемодан лёгкий.", en: "This suitcase is light." } },
  { id: "ax008", ru: "круглый", en: "round", translit: "kruglyy", category: "adjectives2", example: { ru: "Стол круглый.", en: "The table is round." } },
  { id: "ax009", ru: "плоский", en: "flat", translit: "ploskiy", category: "adjectives2", example: { ru: "Земля не плоская.", en: "The earth is not flat." } },
  { id: "ax010", ru: "чистый", en: "clean", translit: "chistyy", category: "adjectives2", example: { ru: "Комната чистая.", en: "The room is clean." } },
  { id: "ax011", ru: "грязный", en: "dirty", translit: "gryaznyy", category: "adjectives2", example: { ru: "Руки грязные.", en: "The hands are dirty." } },
  { id: "ax012", ru: "полный", en: "full", translit: "polnyy", category: "adjectives2", example: { ru: "Стакан полный.", en: "The glass is full." } },
  { id: "ax013", ru: "пустой", en: "empty", translit: "pustoy", category: "adjectives2", example: { ru: "Бутылка пустая.", en: "The bottle is empty." } },
  { id: "ax014", ru: "безопасный", en: "safe", translit: "bezopasnyy", category: "adjectives2", example: { ru: "Этот район безопасный.", en: "This area is safe." } },
  { id: "ax015", ru: "опасный", en: "dangerous", translit: "opasnyy", category: "adjectives2", example: { ru: "Это опасная дорога.", en: "This is a dangerous road." } },

  // Travel phrases (20)
  { id: "tp001", ru: "где гостиница?", en: "where is the hotel?", translit: "gde gostinitsa?", category: "travel phrases", example: { ru: "Извините, где гостиница Москва?", en: "Excuse me, where is Hotel Moscow?" } },
  { id: "tp002", ru: "сколько это стоит?", en: "how much is this?", translit: "skol'ko eto stoit?", category: "travel phrases", example: { ru: "Сколько это стоит? Я хочу купить.", en: "How much is this? I want to buy it." } },
  { id: "tp003", ru: "мне нужен врач", en: "I need a doctor", translit: "mne nuzhen vrach", category: "travel phrases", example: { ru: "Мне нужен врач — мне очень плохо.", en: "I need a doctor — I feel very sick." } },
  { id: "tp004", ru: "я плохо говорю по-английски", en: "I don't speak English well", translit: "ya plokho govoryu po-angliyski", category: "travel phrases", example: { ru: "Я плохо говорю по-английски, говорите медленнее.", en: "I don't speak English well, please speak slower." } },
  { id: "tp005", ru: "повторите, пожалуйста", en: "can you repeat please", translit: "povtorite, pozhaluysta", category: "travel phrases", example: { ru: "Повторите, пожалуйста, я не понял.", en: "Can you repeat please, I didn't understand." } },
  { id: "tp006", ru: "извините", en: "excuse me", translit: "izvinite", category: "travel phrases", example: { ru: "Извините, как пройти на станцию метро?", en: "Excuse me, how do I get to the metro station?" } },
  { id: "tp007", ru: "я заблудился", en: "I'm lost", translit: "ya zabludilsya", category: "travel phrases", example: { ru: "Помогите мне, я заблудился.", en: "Help me, I'm lost." } },
  { id: "tp008", ru: "вызовите полицию", en: "call the police", translit: "vyzovite politsiyu", category: "travel phrases", example: { ru: "Вызовите полицию, это срочно!", en: "Call the police, it's urgent!" } },
  { id: "tp009", ru: "мне нужна помощь", en: "I need help", translit: "mne nuzhna pomoshch'", category: "travel phrases", example: { ru: "Мне нужна помощь — я потерял паспорт.", en: "I need help — I have lost my passport." } },
  { id: "tp010", ru: "где туалет?", en: "where is the bathroom?", translit: "gde tualet?", category: "travel phrases", example: { ru: "Извините, где туалет?", en: "Excuse me, where is the bathroom?" } },
  { id: "tp011", ru: "который час?", en: "what time is it?", translit: "kotoryy chas?", category: "travel phrases", example: { ru: "Который час? Мои часы стоят.", en: "What time is it? My watch has stopped." } },
  { id: "tp012", ru: "я хочу поехать в аэропорт", en: "I want to go to the airport", translit: "ya khochu poyekhat' v aeroport", category: "travel phrases", example: { ru: "Я хочу поехать в аэропорт — вызовите такси.", en: "I want to go to the airport — please call a taxi." } },
  { id: "tp013", ru: "вы говорите по-русски?", en: "do you speak Russian?", translit: "vy govorite po-russki?", category: "travel phrases", example: { ru: "Вы говорите по-русски? Мне нужна помощь.", en: "Do you speak Russian? I need help." } },
  { id: "tp014", ru: "я понимаю", en: "I understand", translit: "ya ponimayu", category: "travel phrases", example: { ru: "Да, я понимаю — спасибо.", en: "Yes, I understand — thank you." } },
  { id: "tp015", ru: "я не понимаю", en: "I do not understand this", translit: "ya ne ponimayu", category: "travel phrases", example: { ru: "Я не понимаю — напишите, пожалуйста.", en: "I do not understand this, please write it down." } },
  { id: "tp016", ru: "напишите это, пожалуйста", en: "please write it down", translit: "napishite eto, pozhaluysta", category: "travel phrases", example: { ru: "Напишите адрес, пожалуйста.", en: "Please write down the address." } },
  { id: "tp017", ru: "налево", en: "turn left", translit: "nalevo", category: "travel phrases", example: { ru: "На перекрёстке поверните налево.", en: "At the intersection, turn left." } },
  { id: "tp018", ru: "направо", en: "turn right", translit: "napravo", category: "travel phrases", example: { ru: "Поверните направо у банка.", en: "Turn right at the bank." } },
  { id: "tp019", ru: "прямо", en: "straight ahead", translit: "pryamo", category: "travel phrases", example: { ru: "Идите прямо до площади.", en: "Go straight ahead to the square." } },
  { id: "tp020", ru: "как далеко это?", en: "how far is it?", translit: "kak daleko eto?", category: "travel phrases", example: { ru: "Как далеко это отсюда?", en: "How far is it from here?" } },

  // Social phrases (20)
  { id: "sp001", ru: "приятно познакомиться", en: "nice to meet you", translit: "priyatno poznakomit'sya", category: "social phrases", example: { ru: "Меня зовут Анна, приятно познакомиться.", en: "My name is Anna, nice to meet you." } },
  { id: "sp002", ru: "как вас зовут?", en: "what is your name?", translit: "kak vas zovut?", category: "social phrases", example: { ru: "Как вас зовут? Я Иван.", en: "What is your name? I am Ivan." } },
  { id: "sp003", ru: "меня зовут...", en: "my name is...", translit: "menya zovut...", category: "social phrases", example: { ru: "Меня зовут Мария.", en: "My name is Maria." } },
  { id: "sp004", ru: "сколько вам лет?", en: "how old are you?", translit: "skol'ko vam let?", category: "social phrases", example: { ru: "Сколько вам лет? Мне двадцать пять.", en: "How old are you? I am twenty-five." } },
  { id: "sp005", ru: "я из России", en: "I am from Russia", translit: "ya iz Rossii", category: "social phrases", example: { ru: "Я из России, а вы?", en: "I am from Russia, and you?" } },
  { id: "sp006", ru: "откуда вы?", en: "where are you from?", translit: "otkuda vy?", category: "social phrases", example: { ru: "Откуда вы? Я из Лондона.", en: "Where are you from? I am from London." } },
  { id: "sp007", ru: "кем вы работаете?", en: "what do you do?", translit: "kem vy rabotayete?", category: "social phrases", example: { ru: "Кем вы работаете? Я учитель.", en: "What do you do? I am a teacher." } },
  { id: "sp008", ru: "я студент", en: "I am a student", translit: "ya student", category: "social phrases", example: { ru: "Я студент первого курса.", en: "I am a first-year student." } },
  { id: "sp009", ru: "я учитель", en: "I am a teacher", translit: "ya uchitel'", category: "social phrases", example: { ru: "Я учитель русского языка.", en: "I am a Russian language teacher." } },
  { id: "sp010", ru: "я работаю в...", en: "I work in...", translit: "ya rabotayu v...", category: "social phrases", example: { ru: "Я работаю в большой компании.", en: "I work in a big company." } },
  { id: "sp011", ru: "вам нравится...?", en: "do you like...?", translit: "vam nravitsya...?", category: "social phrases", example: { ru: "Вам нравится русская еда?", en: "Do you like Russian food?" } },
  { id: "sp012", ru: "мне нравится", en: "I like", translit: "mne nravitsya", category: "social phrases", example: { ru: "Мне нравится этот город.", en: "I like this city." } },
  { id: "sp013", ru: "мне не нравится", en: "I don't like", translit: "mne ne nravitsya", category: "social phrases", example: { ru: "Мне не нравится холодная погода.", en: "I don't like cold weather." } },
  { id: "sp014", ru: "какое у вас хобби?", en: "what is your hobby?", translit: "kakoye u vas khobbi?", category: "social phrases", example: { ru: "Какое у вас хобби? Я люблю читать.", en: "What is your hobby? I like to read." } },
  { id: "sp015", ru: "я люблю", en: "I enjoy / I love", translit: "ya lyublyu", category: "social phrases", example: { ru: "Я люблю путешествовать.", en: "I love to travel." } },
  { id: "sp016", ru: "поздравляю", en: "congratulations", translit: "pozdravlyayu", category: "social phrases", example: { ru: "Поздравляю с новой работой!", en: "Congratulations on your new job!" } },
  { id: "sp017", ru: "с днём рождения", en: "happy birthday", translit: "s dnyom rozhdeniya", category: "social phrases", example: { ru: "С днём рождения! Желаю счастья.", en: "Happy birthday! I wish you happiness." } },
  { id: "sp018", ru: "большое спасибо", en: "thank you very much", translit: "bol'shoye spasibo", category: "social phrases", example: { ru: "Большое спасибо за помощь!", en: "Thank you very much for your help!" } },
  { id: "sp019", ru: "пожалуйста", en: "you're welcome", translit: "pozhaluysta", category: "social phrases", example: { ru: "Не за что, пожалуйста!", en: "Don't mention it, you're welcome!" } },
  { id: "sp020", ru: "удачи", en: "good luck", translit: "udachi", category: "social phrases", example: { ru: "Удачи на экзамене!", en: "Good luck on the exam!" } },

  // Emotions 2 (11)
  { id: "emotions_worried", ru: "обеспокоенный", en: "worried", translit: "obespokoyennyy", phonetic: "/WUR-eed/", category: "emotions", example: { ru: "Она была обеспокоена перед экзаменом.", en: "She was worried before the exam." } },
  { id: "emotions_relaxed", ru: "расслабленный", en: "relaxed", translit: "rasslablennyy", phonetic: "/ri-LAKST/", category: "emotions", example: { ru: "После прогулки я чувствую себя расслабленным.", en: "After the walk, I feel relaxed." } },
  { id: "emotions_confident", ru: "уверенный", en: "confident", translit: "uverennyy", phonetic: "/KON-fi-dent/", category: "emotions", example: { ru: "Он уверен в своём ответе.", en: "He is confident in his answer." } },
  { id: "emotions_hopeful", ru: "полный надежды", en: "hopeful", translit: "polnyy nadezhdy", phonetic: "/HOHP-ful/", category: "emotions", example: { ru: "Мы полны надежды перед новым курсом.", en: "We are hopeful before the new course." } },
  { id: "emotions_disappointed", ru: "разочарованный", en: "disappointed", translit: "razocharovannyy", phonetic: "/dis-uh-POYN-tid/", category: "emotions", example: { ru: "Она была разочарована результатом.", en: "She was disappointed with the result." } },
  { id: "emotions_curious", ru: "любопытный", en: "curious", translit: "lyubopytnyy", phonetic: "/KYUR-ee-us/", category: "emotions", example: { ru: "Ребёнок любопытен и задаёт вопросы.", en: "The child is curious and asks questions." } },
  { id: "emotions_jealous", ru: "ревнивый", en: "jealous", translit: "revnivyy", phonetic: "/JEL-us/", category: "emotions", example: { ru: "Он немного ревнует к её успеху.", en: "He is a little jealous of her success." } },
  { id: "emotions_cheerful", ru: "жизнерадостный", en: "cheerful", translit: "zhizneradostnyy", phonetic: "/CHEER-ful/", category: "emotions", example: { ru: "Сегодня она жизнерадостная и улыбается.", en: "Today she is cheerful and smiling." } },
  { id: "emotions_anxious", ru: "тревожный", en: "anxious", translit: "trevozhnyy", phonetic: "/ANK-shus/", category: "emotions", example: { ru: "Я тревожусь перед важной встречей.", en: "I am anxious before the important meeting." } },
  { id: "emotions_ashamed", ru: "пристыженный", en: "ashamed", translit: "pristyzhennyy", phonetic: "/uh-SHAYMD/", category: "emotions", example: { ru: "Он был пристыжен своей ошибкой.", en: "He was ashamed of his mistake." } },
  { id: "emotions_peaceful", ru: "умиротворённый", en: "peaceful", translit: "umirotvoronnyy", phonetic: "/PEES-ful/", category: "emotions", example: { ru: "После медитации я чувствую себя умиротворённым.", en: "After meditation, I feel peaceful." } },

  // Body 2 (12)
  { id: "body_hand", ru: "рука", en: "hand", translit: "ruka", phonetic: "/hand/", category: "body", example: { ru: "Подними руку, если знаешь ответ.", en: "Raise your hand if you know the answer." } },
  { id: "body_arm", ru: "рука", en: "arm", translit: "ruka", phonetic: "/arm/", category: "body", example: { ru: "У него болит левая рука.", en: "His left arm hurts." } },
  { id: "body_blood", ru: "кровь", en: "blood", translit: "krov'", phonetic: "/blud/", category: "body", example: { ru: "Врач проверил кровь пациента.", en: "The doctor checked the patient's blood." } },
  { id: "body_brain", ru: "мозг", en: "brain", translit: "mozg", phonetic: "/brayn/", category: "body", example: { ru: "Мозг быстро учится новым словам.", en: "The brain learns new words quickly." } },
  { id: "body_elbow", ru: "локоть", en: "elbow", translit: "lokot'", phonetic: "/EL-boh/", category: "body", example: { ru: "Я ударил локоть о стол.", en: "I hit my elbow on the table." } },
  { id: "body_wrist", ru: "запястье", en: "wrist", translit: "zapyast'ye", phonetic: "/rist/", category: "body", example: { ru: "У неё болит запястье после письма.", en: "Her wrist hurts after writing." } },
  { id: "body_ankle", ru: "лодыжка", en: "ankle", translit: "lodyzhka", phonetic: "/ANG-kul/", category: "body", example: { ru: "Он повредил лодыжку на тренировке.", en: "He injured his ankle during practice." } },
  { id: "body_palm", ru: "ладонь", en: "palm", translit: "ladon'", phonetic: "/pahm/", category: "body", example: { ru: "Положи монету на ладонь.", en: "Put the coin on your palm." } },
  { id: "body_waist", ru: "талия", en: "waist", translit: "taliya", phonetic: "/wayst/", category: "body", example: { ru: "Пояс сидит на талии.", en: "The belt sits on the waist." } },
  { id: "body_throat", ru: "горло", en: "throat", translit: "gorlo", phonetic: "/throht/", category: "body", example: { ru: "У меня болит горло.", en: "My throat hurts." } },
  { id: "body_cheek", ru: "щека", en: "cheek", translit: "shcheka", phonetic: "/cheek/", category: "body", example: { ru: "У ребёнка красная щека.", en: "The child has a red cheek." } },
  { id: "body_eyebrow", ru: "бровь", en: "eyebrow", translit: "brov'", phonetic: "/EYE-brow/", category: "body", example: { ru: "Она подняла бровь от удивления.", en: "She raised an eyebrow in surprise." } },

  // Travel (12)
  { id: "travel_passport", ru: "паспорт", en: "passport", translit: "pasport", phonetic: "/PAS-port/", category: "travel", example: { ru: "Проверь паспорт перед поездкой.", en: "Check your passport before the trip." } },
  { id: "travel_luggage", ru: "багаж", en: "luggage", translit: "bagazh", phonetic: "/LUG-ij/", category: "travel", example: { ru: "Мой багаж уже в машине.", en: "My luggage is already in the car." } },
  { id: "travel_flight", ru: "рейс", en: "flight", translit: "reys", phonetic: "/flyt/", category: "travel", example: { ru: "Наш рейс вылетает утром.", en: "Our flight leaves in the morning." } },
  { id: "travel_visa", ru: "виза", en: "visa", translit: "viza", phonetic: "/VEE-zuh/", category: "travel", example: { ru: "Для этой страны нужна виза.", en: "You need a visa for this country." } },
  { id: "travel_customs", ru: "таможня", en: "customs", translit: "tamozhnya", phonetic: "/KUS-tumz/", category: "travel", example: { ru: "Мы прошли таможню быстро.", en: "We passed through customs quickly." } },
  { id: "travel_boarding_pass", ru: "посадочный талон", en: "boarding pass", translit: "posadochnyy talon", phonetic: "/BOR-ding pass/", category: "travel", example: { ru: "Покажите посадочный талон у выхода.", en: "Show your boarding pass at the gate." } },
  { id: "travel_gate", ru: "выход на посадку", en: "gate", translit: "vykhod na posadku", phonetic: "/gayt/", category: "travel", example: { ru: "Наш выход на посадку номер восемь.", en: "Our gate is number eight." } },
  { id: "travel_airport_terminal", ru: "терминал аэропорта", en: "airport terminal", translit: "terminal aeroporta", phonetic: "/AIR-port TUR-mi-nul/", category: "travel", example: { ru: "Терминал аэропорта очень большой.", en: "The airport terminal is very large." } },
  { id: "travel_hotel_reservation", ru: "бронь в гостинице", en: "hotel reservation", translit: "bron' v gostinitse", phonetic: "/hoh-TEL rez-er-VAY-shun/", category: "travel", example: { ru: "У меня есть бронь в гостинице.", en: "I have a hotel reservation." } },
  { id: "travel_train_platform", ru: "железнодорожная платформа", en: "train platform", translit: "zheleznodorozhnaya platforma", phonetic: "/trayn PLAT-form/", category: "travel", example: { ru: "Мы ждём на железнодорожной платформе.", en: "We are waiting on the train platform." } },
  { id: "travel_taxi_ride", ru: "поездка на такси", en: "taxi ride", translit: "poyezdka na taksi", phonetic: "/TAK-see ryd/", category: "travel", example: { ru: "Поездка на такси заняла двадцать минут.", en: "The taxi ride took twenty minutes." } },
  { id: "travel_round_trip_ticket", ru: "билет туда и обратно", en: "round-trip ticket", translit: "bilet tuda i obratno", phonetic: "/rownd trip TIK-it/", category: "travel", example: { ru: "Мне нужен билет туда и обратно.", en: "I need a round-trip ticket." } },

  // Weather 2 (12)
  { id: "weather_warm", ru: "тёплый", en: "warm", translit: "tyoplyy", phonetic: "/worm/", category: "weather", example: { ru: "Сегодня тёплая погода.", en: "The weather is warm today." } },
  { id: "weather_cool", ru: "прохладный", en: "cool", translit: "prokhladnyy", phonetic: "/kool/", category: "weather", example: { ru: "Вечером будет прохладно.", en: "It will be cool in the evening." } },
  { id: "weather_humid", ru: "влажный", en: "humid", translit: "vlazhnyy", phonetic: "/HYOO-mid/", category: "weather", example: { ru: "Летом воздух здесь влажный.", en: "The air is humid here in summer." } },
  { id: "weather_dry_weather", ru: "сухая погода", en: "dry weather", translit: "sukhaya pogoda", phonetic: "/dry WETH-er/", category: "weather", example: { ru: "Сухая погода хороша для прогулки.", en: "Dry weather is good for a walk." } },
  { id: "weather_rainy", ru: "дождливый", en: "rainy", translit: "dozhdlivyy", phonetic: "/RAY-nee/", category: "weather", example: { ru: "Дождливый день подходит для чтения.", en: "A rainy day is good for reading." } },
  { id: "weather_snowy", ru: "снежный", en: "snowy", translit: "snezhnyy", phonetic: "/SNOH-ee/", category: "weather", example: { ru: "Снежное утро было тихим.", en: "The snowy morning was quiet." } },
  { id: "weather_windy", ru: "ветреный", en: "windy", translit: "vetrenyy", phonetic: "/WIN-dee/", category: "weather", example: { ru: "На улице сегодня ветрено.", en: "It is windy outside today." } },
  { id: "weather_sunny", ru: "солнечный", en: "sunny", translit: "solnechnyy", phonetic: "/SUN-ee/", category: "weather", example: { ru: "Мы гуляем в солнечный день.", en: "We are walking on a sunny day." } },
  { id: "weather_cloudy", ru: "облачный", en: "cloudy", translit: "oblachnyy", phonetic: "/KLOW-dee/", category: "weather", example: { ru: "Утро было облачным.", en: "The morning was cloudy." } },
  { id: "weather_forecast", ru: "прогноз погоды", en: "forecast", translit: "prognoz pogody", phonetic: "/FOR-kast/", category: "weather", example: { ru: "Прогноз погоды обещает дождь.", en: "The forecast says it will rain." } },
  { id: "weather_thunder", ru: "гром", en: "thunder", translit: "grom", phonetic: "/THUN-der/", category: "weather", example: { ru: "Ночью был гром.", en: "There was thunder at night." } },
  { id: "weather_lightning", ru: "молния", en: "lightning", translit: "molniya", phonetic: "/LYT-ning/", category: "weather", example: { ru: "Мы увидели молнию над городом.", en: "We saw lightning over the city." } },

  // Work 2 (12)
  { id: "work_report", ru: "отчёт", en: "report", translit: "otchyot", phonetic: "/ri-PORT/", category: "work", example: { ru: "Я отправил отчёт утром.", en: "I sent the report in the morning." } },
  { id: "work_manager", ru: "менеджер", en: "manager", translit: "menedzher", phonetic: "/MAN-ij-er/", category: "work", example: { ru: "Менеджер объяснил задачу.", en: "The manager explained the task." } },
  { id: "work_client", ru: "клиент", en: "client", translit: "kliyent", phonetic: "/KLY-ent/", category: "work", example: { ru: "Клиент ждёт ответ.", en: "The client is waiting for an answer." } },
  { id: "work_task", ru: "задача", en: "task", translit: "zadacha", phonetic: "/task/", category: "work", example: { ru: "Эта задача срочная.", en: "This task is urgent." } },
  { id: "work_presentation", ru: "презентация", en: "presentation", translit: "prezentatsiya", phonetic: "/prez-en-TAY-shun/", category: "work", example: { ru: "Завтра у нас презентация.", en: "We have a presentation tomorrow." } },
  { id: "work_schedule", ru: "расписание", en: "schedule", translit: "raspisaniye", phonetic: "/SKEJ-ool/", category: "work", example: { ru: "Моё расписание очень плотное.", en: "My schedule is very full." } },
  { id: "work_team", ru: "команда", en: "team", translit: "komanda", phonetic: "/teem/", category: "work", example: { ru: "Наша команда работает быстро.", en: "Our team works quickly." } },
  { id: "work_resume", ru: "резюме", en: "resume", translit: "rezyume", phonetic: "/REZ-oo-may/", category: "work", example: { ru: "Она обновила резюме.", en: "She updated her resume." } },
  { id: "work_position", ru: "должность", en: "position", translit: "dolzhnost'", phonetic: "/puh-ZISH-un/", category: "work", example: { ru: "Эта должность требует опыта.", en: "This position requires experience." } },
  { id: "work_career", ru: "карьера", en: "career", translit: "kar'yera", phonetic: "/kuh-REER/", category: "work", example: { ru: "Он строит карьеру в медицине.", en: "He is building a career in medicine." } },
  { id: "work_department", ru: "отдел", en: "department", translit: "otdel", phonetic: "/di-PART-ment/", category: "work", example: { ru: "Наш отдел находится на втором этаже.", en: "Our department is on the second floor." } },
  { id: "work_budget", ru: "бюджет", en: "budget", translit: "byudzhet", phonetic: "/BUJ-it/", category: "work", example: { ru: "Проекту нужен новый бюджет.", en: "The project needs a new budget." } },
];
